### ISSUE TITLE
KeepassXC crashing in Enforce Mode

### ISSUE THREAD

**Issue by abhigit23** [roddhjav/apparmor.d#102]
KeepassXC crashing every time when I open the database
AppArmor is updated and set to the Enforce Mode
 
    $ sudo aa-log keepassxc
```DENIED  keepassxc file_inherit /home/mystik/.local/share/gvfs-metadata/root comm=keepassxc requested_mask=r denied_mask=r
DENIED  keepassxc file_inherit /home/mystik/.local/share/gvfs-metadata/root-9c234de1.log comm=keepassxc requested_mask=r denied_mask=r
DENIED  keepassxc open /dev/tty comm=keepassxc requested_mask=r denied_mask=r
DENIED  keepassxc open /usr/share/glib-2.0/schemas/gschemas.compiled comm=keepassxc requested_mask=r denied_mask=r
DENIED  keepassxc open /usr/share/qt/translations/qtbase_en.qm comm=keepassxc requested_mask=r denied_mask=r
DENIED  keepassxc open /usr/bin/ comm=keepassxc requested_mask=r denied_mask=r
DENIED  keepassxc mkdir /run/user/1000/app/org.keepassxc.KeePassXC/ comm=keepassxc requested_mask=c denied_mask=c
```

[aa-log output](https://privatebin.net/?f1c462d3ffa5b6fb#9MFnomZ7atGs47g366yHSEQ6XXx45prxVFwsj6YFnHvo)

**Comment by roddhjav** [comment]
Thanks for your issue & for the log. Can you switch to complain mode send the log again: as the enforce mode block the program it is way harder to debug it.

**Comment by abhigit23** [comment]
Sure, here is the full [`aa-log`](https://privatebin.net/?ec1b4d9228ba3c4b#231qGNNfag65Wz1uP8y8u82TcNWHQ12XNf1rDKegwVem) output in Complain Mode

Thanks for your help!

**Comment by roddhjav** [comment]
Thanks. I fully rewritten the profile. (I don't use it too much as I am more a [pass](https://github.com/roddhjav/pass-import) person).

You will need to [personalize](https://github.com/roddhjav/apparmor.d#personalisation) the  `XDP_PASSWORD_STORE_DIR` or `user_password_store_dirs` variable with the directory where you store your password db. In your context, it seems to be:
```
@{user_password_store_dirs}+="@{MOUNTS}/Users/*/Documents/"
```

**Comment by roddhjav** [comment]
I integrated the rest of your logs. I would advise you to keep the (default) complain mode for all the profiles for at least a month. So you can check if everything works fine without breaking an app.

Also, for pacman integration with yay, you need to personalize the `user_pkg_dirs` variable with: 
```
@{user_pkg_dirs}+=@{user_cache_dirs}/yay/
```

**Comment by abhigit23** [comment]
> Thanks. I fully rewritten the profile. (I don't use it too much as I am more a [pass](https://github.com/roddhjav/pass-import) person).
> 
> You will need to [personalize](https://github.com/roddhjav/apparmor.d#personalisation) the `XDP_PASSWORD_STORE_DIR` or `user_password_store_dirs` variable with the directory where you store your password db. In your context, it seems to be:
> 
> ```
> @{user_password_store_dirs}+="@{MOUNTS}/Users/*/Documents/"
> ```

Thanks, it's fixed now, no more crashing, and have access to the db. (pass seems interesting so I'll definitely check it out later)
Also thanks for your advice, I'll keep on complain mode from now on and open issues if I find any.
