### ISSUE TITLE
allow read $HOME/.terminfo

### ISSUE THREAD

**Issue by vbauerster** [roddhjav/apparmor.d#103]
I think common programs that are expected to be run by user should be allowed to:

```
owner @{HOME}/.terminfo/[0-9]*/* r,
```

That's already a case for example for:
https://github.com/roddhjav/apparmor.d/blob/1f16025c10086092425e19bace3fe300f6266105/apparmor.d/groups/children/child-pager#L35

but not for git:
```
❯ aa-log git
ALLOWED git open /home/vbauer/.terminfo/74/tmux-256color comm=sh requested_mask=r denied_mask=r
```

**Comment by roddhjav** [comment]
I am wondering what would be the best action here. It seems to be quite specific to your setup, so it might not be needed to be added on all console program.
