### ISSUE TITLE
Bluez5 HSP/HFP profile error

### ISSUE THREAD

**Issue by abhigit23** [roddhjav/apparmor.d#104]
I can't use my BT earphone mic as there are no HSP/HFP profiles present to select while AppArmor is enabled
AppArmor is in default Complain Mode

    $ systemctl status bluetooth
![image](https://user-images.githubusercontent.com/88484339/212905162-f5ab59af-cd29-467d-8749-b10499b1d785.png)

Wireplumber falling back to use Bluez5 legacy API
A2DP sink profiles are working fine

    $ systemctl status --user wireplumber
![image](https://user-images.githubusercontent.com/88484339/212905737-96387779-6df1-4c18-8eec-3ff1ab77336f.png)

I ran `aa-log` but found nothing related to Bluez or Bluetooth there

**Comment by roddhjav** [comment]
Can you profile the full log to see what's causing the pb in AA log. If it is just a missing profile, that should not be too complex to fix.

**Comment by abhigit23** [comment]
> Can you profile the full log to see what's causing the pb in AA log. If it is just a missing profile, that should not be too complex to fix.

Here are the logs :-
[aa-log](https://privatebin.net/?d4c93a5cd3af2c8a#A1htUAv2rvhiZvXu6VPVEHGxSdGBP5MxZBdyoUVHG4zP)
[journalctl -b | grep -i bluetooth](https://privatebin.net/?9b7133435573abf4#7nDVbuXv5q2XPBSmFME3cC5AYhMdypceA8wPBTJrnj1B)
[journalctl -b | grep -i wireplumber](https://privatebin.net/?008e44b3a7129561#GQPMDoA8CNvCqYmc8UBdycMpa5uJg4Ki1FAhhUeXMMaW)

HSP/HFP profiles not showing up in Gnome sound settings when AppArmor is enabled. I have to unload AppArmor profiles, restart the Bluetooth service then those audio profiles show up in the settings.
Hope it helps!

**Comment by roddhjav** [comment]
Tell me if it changed something. The logs does not show that much sound related issues. I only added access to a new hardware ID in `wireplumber` (that was not blocked anyway as AA is is complain mode).

**Comment by abhigit23** [comment]
It's still the same, can't get the HSP/HPF profiles in the settings with AA enabled

Gnome sound settings [with AA enabled](https://privatebin.net/?8fc127738eff7d38#6Wqp58KF27CQKeoppDZgB2GwHPUzumJs1A1v5wNqi1pU)

Gnome sound settings [after unloading profiles and restart Bluetooth service](https://privatebin.net/?a8ca9637b5823f3f#5heud4ERvtHbmA3z8Kb6wn8CCB79iSrgdiuurGmEWgfU) - image 1/2
[image 2/2](https://privatebin.net/?d3ed8ef86b9946a7#74aCDkgAgCeci7K8iE91xBnDabCJubPLVgma5PJv8oBt)

What has changed:-
`xdg-desktop-portal` warning has gone from wireplumber service
[Wireplumber with AA](https://privatebin.net/?0480d32abf688e77#AodwobewKs5vfV2dXENQAh9AJCsRuVAgCJWBtJgrLS1D)
[Wireplumber after unloading profiles and restarting the service](https://privatebin.net/?60b6a5c9ff27b959#3bMneN1WV8FnujCWPQkQv1qcWpMgQmTYQj9EkG8Y2bE9)

`Unable to get Hands-Free Voice gateway SDP record: Host is down` seems to have fixed in Bluetooth service
[Bluetooth service with/without AA enabled](https://privatebin.net/?03b5d75d20e8de00#6gDYFfYgDpt4R46jDg2CXESY5yu2KiR8jL3dWppS2ZHM)

Full audit log is here:-
[journalctl -b | grep -i audit](https://privatebin.net/?2a5b154502c6787b#ERmBfkdZQ2HnFVci87kdxMNNYHMJ6AYu3MPecr7756CN)

**Comment by roddhjav** [comment]
Can you try again now. I [made a few changes](https://github.com/roddhjav/apparmor.d/commit/64ad329dd9d81658ce778b596740397dc39013e2) that could help here.

**Comment by abhigit23** [comment]
It's still not working. I updated apparmor.d, restarted the system, and then connected the Bluetooth but only got A2DP profiles in the settings. The new workaround is to restart the Bluetooth service after boot seems to have fixed the issue. So now, I have to restart the service each time after booting to get the HSP/HFP profiles available in the settings.

**Comment by roddhjav** [comment]
As all access requested by AA have been given, I am afraid I cannot help you much more on this. This may be up to you to figure out what is the actual issue.
