### ISSUE TITLE
Manjaro install issue

### ISSUE THREAD

**Issue by Cherkah** [roddhjav/apparmor.d#107]
pacman:

==> Extraction des sources…
  -> Création d’une copie de travail du dépot apparmor.d-git git…
Clonage dans 'apparmor.d-git'...
fait.
==> Lancement de prepare()…
Set the configuration for manjarolinux.
 - Ignore profiles/files in dists/ignore/main.ignore
 - Ignore profiles/files in dists/ignore/manjarolinux.ignore
./configure: ligne 34: dists/ignore/manjarolinux.ignore: Aucun fichier ou dossier de ce type
Error: removing ignored profiles
==> ERREUR : Une erreur s’est produite dans prepare().
    Abandon…

regard

**Comment by roddhjav** [comment]
That's is normal, Manjaro is not supported.

Here is the minimum you will need to do to add support: https://github.com/roddhjav/apparmor.d/pull/88
