### ISSUE TITLE
error: could not get current working directory

### ISSUE THREAD

**Issue by vbauerster** [roddhjav/apparmor.d#111]
There is error while updating the package:
```
:: Processing package changes...
error: could not get current working directory
```

Is it ok?

OS: arch linux
Aur manager: paru

**Comment by roddhjav** [comment]
It is a feature. See https://github.com/roddhjav/apparmor.d/issues/99#issuecomment-1382899243
I will shortly sum up all these in a documentation page.

**Comment by roddhjav** [comment]
For reference: https://apparmor.pujol.io/issues/#pacman-could-not-get-current-working-directory
