### ISSUE TITLE
systemd-journald unconfined

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#122]
I noticed that `systemd-journald` is unconfined in my Arch Linux system. The profile is in enforce mode here but it doesn't show up among the "processes are in enforce mode" in `aa-status`. And `ps auxZ` reports:

`unconfined                      root         314  0.0  0.0 111156 10508 ?        Ss   13:23   0:00 /usr/lib/systemd/systemd-journald`

I added the following `override.conf` to `/etc/systemd/system/systemd-journald`:

```
[Service]
AppArmorProfile=/etc/apparmor.d/systemd-journald
```
but that didn't help after a reboot.

What am I missing?

EDIT: The same observation with `systemd-udevd`:
`unconfined                      root         382  0.0  0.0  34412 11492 ?        Ss   17:27   0:00 /usr/lib/systemd/systemd-udevd`

while `systemd-timesyncd` and `systemd-logind` are confined.

**Comment by roddhjav** [comment]
Hi, You need to ensure that the apparmor profile are loaded before the start of `systemd-journald`. When using the package install, this is already taking care of by some systemd overwriting. In the `systemd` folder you have:

https://github.com/roddhjav/apparmor.d/blob/3eb8dd28113d9f59158f69c3b2ca04984a023a3b/systemd/system/systemd-journald.service#L1-L2

It is installed under `/usr/lib/systemd/system/systemd-journald.service.d/apparmor.conf`

**Comment by curiosityseeker** [comment]
Ah, thanks! Yes, `systemd-journald`is now confined!

However, when I tried the same approach for `systemd-udevd` my system didn't boot anymore although the profile is in complain mode.

**Comment by roddhjav** [comment]
Yes, `systemd-udevd` is not configured to be confined as it is know to break some boot . See #74

**Comment by curiosityseeker** [comment]
I understand. Sorry, I hadn't seen those issues, I should have performed a search.
