### ISSUE TITLE
build succeeds despite "make: git: No such file or directory"

### ISSUE THREAD

**Issue by cboltz** [roddhjav/apparmor.d#132]
During build, I see the following message twice:

    make: git: No such file or directory

My guess is that this comes from the following line in Makefile:

    VERSION := 0.$(shell git rev-list --count HEAD)-1

Interestingly, the build and install continue as if nothing has happened.

I'd expect that such an error fails the build.

**Comment by cboltz** [comment]
After adding `BuildRequires: git-core`, I get the next failure:

    fatal: not a git repository (or any of the parent directories): .git

(not too surprising because the tarball generated with OBS _service doesn't include the `.git` directory - but this issue will also bite you once/if you provide release tarballs)

If I understand the Makefile right, `VERSION` is only used for Ubuntu packaging stuff.

Maybe I should revoke my `I'd expect that such an error fails the build.` request  ;-) - but please make sure that the code that actually uses `VERSION` fails if it is empty or broken.

**Comment by roddhjav** [comment]
I have hacked around the makefile and now git will only be required for ubuntu based dev build (`make dpkg`)
