### ISSUE TITLE
Can't use git clone or git pull commands

### ISSUE THREAD

**Issue by abhigit23** [roddhjav/apparmor.d#133]
```$ git clone https://github.com/roddhjav/apparmor.d.git```

     fatal: could not create work tree dir 'apparmor.d': Permission denied

```$ git pull```
     
     fatal: not a git repository (or any parent up to mount point /)
     Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

When I tried to git pull from the folder I got the above error.

Logs are here -> [aa-log](https://privatebin.net/?5d48261dbdcb2f53#DJe8vnyozEJC5LjRCWEQ4FTwafPxp9PvnkXYkykbNdPW)

**Comment by roddhjav** [comment]
From the log I see to thing:
1. You need to set your project directory (`XDG_PROJECTS_DIR`). See https://apparmor.pujol.io/configuration/#personal-directories
2. While testing, if something get wrong, you need to put the profile in complain mode, to that you can investigate and it does not block your program.

**Comment by abhigit23** [comment]
Thanks that solved the issue for git commands.

I found another issue with gpg. I can't update flatpak apps
```$ flatpak update```

     Warning: While pulling runtime/org.gnome.Platform.Locale/x86_64/43 from remote flathub: Commit 917d8cf043a98b5f45707fffc2962eb22bf600197a3b07f5b989e1266c55dc87: Signature made Mon 27 Mar 2023 04:02:55 AM IST using RSA key ID 562702E9E3ED7EE8
     Can't check signature: public key not found
     Error: While pulling runtime/org.gnome.Platform/x86_64/43 from remote flathub: Commit 7b401f1224aa517e8abcf40c3c99e9a9a669ac8b7568674ba5de32e5a7b6ecc7: Signature made Mon 27 Mar 2023 04:01:59 AM IST using RSA key ID 562702E9E3ED7EE8
     Can't check signature: public key not found
  
```$ sudo aa-log```

     DENIED  gpg open /tmp/ostree-gpg-KyyfUZ/pubring.gpg comm=gpg requested_mask=r denied_mask=r class=file
     DENIED  gpg mknod /tmp/ostree-gpg-KyyfUZ/.#lk0x0000555c2ac69ee0.archlinux.4612 comm=gpg requested_mask=c denied_mask=c class=file
     DENIED  gpg mknod /tmp/ostree-gpg-KyyfUZ/.#lk0x000055eb66d5aee0.archlinux.4616 comm=gpg requested_mask=c denied_mask=c class=file
     DENIED  gpg mknod /tmp/ostree-gpg-KyyfUZ/.#lk0x000055eb66d5b870.archlinux.4616 comm=gpg requested_mask=c denied_mask=c class=file
     DENIED  gpg open /tmp/ostree-gpg-9S3IB4/pubring.gpg comm=gpg requested_mask=r denied_mask=r class=file
     DENIED  gpg mknod /tmp/ostree-gpg-9S3IB4/.#lk0x00005588ea561ee0.archlinux.4635 comm=gpg requested_mask=c denied_mask=c class=file
     DENIED  gpg mknod /tmp/ostree-gpg-9S3IB4/.#lk0x000055fd3af02ee0.archlinux.4639 comm=gpg requested_mask=c denied_mask=c class=file
     DENIED  gpg mknod /tmp/ostree-gpg-9S3IB4/.#lk0x000055fd3af03870.archlinux.4639 comm=gpg requested_mask=c denied_mask=c class=file
     DENIED  gpg open /tmp/ostree-gpg-UOOUyG/pubring.gpg comm=gpg requested_mask=r denied_mask=r class=file
     DENIED  gpg mknod /tmp/ostree-gpg-UOOUyG/.#lk0x000055bed7a48ee0.archlinux.4655 comm=gpg requested_mask=c denied_mask=c class=file
     DENIED  gpg mknod /tmp/ostree-gpg-UOOUyG/.#lk0x0000559abb82eee0.archlinux.4659 comm=gpg requested_mask=c denied_mask=c class=file
     DENIED  gpg mknod /tmp/ostree-gpg-UOOUyG/.#lk0x0000559abb82f870.archlinux.4659 comm=gpg requested_mask=c denied_mask=c class=file
