### ISSUE TITLE
Can't startx

### ISSUE THREAD

**Issue by bcmertz** [roddhjav/apparmor.d#135]
`startx` from tty fails silently

logs here: https://privatebin.net/?90bde43f3b419144#CUSYDuVTZUFqPwFyFK8iEARUhf8gnG1AMFyJuKnU4Vu5

I have some code in my .profile and .xinitrc related to setting some environmental variable related to the chosen WM that may or may not be related. I will keep digging into this to see if I find anything, but any insight is greatly appreciated :)

**Comment by nobody43** [comment]
Xorg-related profiles are not actively maintained. I'm doing the refresh on Xubuntu LTS, hopefully it will be done in a month or two.

To make it work right now, either `complain` and `rPUx` all these profiles, or if it doesn't work remove them altogether.

**Comment by bcmertz** [comment]
Sounds good, thank you for the clarification! Best of luck with the refresh :)

**Comment by roddhjav** [comment]
Add the `attach_disconnected` flag on `startx` and move it in complain mode and that should at least unblock you.

> Xorg-related profiles are not actively maintained. 

This is kind of true. Most of the work focus on the future, not on the past. Meanwhile, a lot of DE still use xorg. So, I am slowly starting to work on some kde related profiles. Right now, xorg itself should work fine. The complexity is in all the software that can start it: sddm, gdm, startx, with all the config specific to some DE.

**Comment by bcmertz** [comment]
Hi @roddhjav , that worked for me to get up and running, much appreciated!
