### ISSUE TITLE
Firefox not confined

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#136]
I'm running EndeavourOS with KDE as a test in a Virtualbox VM (and btw.: today was the first time that it booted properly thanks to the recent commits - great stuff!!! ). I noticed that after launching Firefox it didn't show up in `sudo aa-status` and was marked as unconfined in `ps auxZ`.

However, Firefox was confined after adding `/usr/lib/firefox/firefox` to @{exec_path} although the existing `@{firefox_lib_dirs}/@{firefox_name}` should actually translate to that path. I'm not quite sure why that didn't work.

**Comment by roddhjav** [comment]
I have the same issue in KDE (but not in gnome, they might not start the same file). That comes [from the configure script](https://github.com/roddhjav/apparmor.d/blob/cbc1d8faf3d86703b23672ed6589f2775d8f24bb/configure#L136). I need to take time and fix it.

**Comment by roddhjav** [comment]
That should be fixed now.
