### ISSUE TITLE
Running makepkg fails

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#151]
After the recent commits running `makepkg -si` fails:

```
makepkg -si
==> Making package: apparmor.d-git 0.866-2 (Thu Apr 20 12:18:58 2023)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating apparmor.d-git git repo...
==> Validating source files with sha512sums...
    apparmor.d-git ... Skipped
==> Extracting sources...
  -> Creating working copy of apparmor.d-git git repo...
Reset branch 'makepkg'
==> Starting prepare()...
/home/curiosityseeker/apparmor.d-git/PKGBUILD: line 23: ./configure: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
```

Deleting the folder and executing `git clone https://aur.archlinux.org/apparmor.d-git.git` again didn't help.

**Comment by roddhjav** [comment]
My bad, I forgot to update the pkgbuild in the AUR to the most recent building changes. It should work fine now.

**Comment by curiosityseeker** [comment]
Thanks, it works now! Although `git pull` caused an error as I had removed the --complain flag in the PKGBUILD. `git fetch --all` and `git reset --hard origin/master` fixed that problem. 

However, how do I set the profiles into enforce mode now? https://apparmor.pujol.io/enforce/ is not yet updated.

**Comment by roddhjav** [comment]
Yea, that because of [an issue in CI that fail](https://gitlab.com/roddhjav/apparmor.d/-/pipelines/842714890) before doc deployment. Meanwhile, you can see the doc here: https://github.com/roddhjav/apparmor.d/blob/main/docs/enforce.md

**Comment by roddhjav** [comment]
CI fixed and new doc version deployed.
