### ISSUE TITLE
Question: why 'owner @{MOUNTS}' rules do not apply?

### ISSUE THREAD

**Issue by vbauerster** [roddhjav/apparmor.d#152]
```
ALLOWED gvfs-udisks2-volume-monitor open /run/media/user/ENTWARE/ comm=gvfs-udisks2-vo requested_mask=r denied_mask=r class=file
ALLOWED gvfs-udisks2-volume-monitor open /run/media/user/ENTWARE/ comm=pool requested_mask=r denied_mask=r class=file
ALLOWED gnome-shell-hotplug-sniffer open /run/media/user/ENTWARE/ comm=pool requested_mask=r denied_mask=r class=file
```

Doesn't following rules should suppress above messages?

https://github.com/roddhjav/apparmor.d/blob/789e1ddf8bdb0ae13ec1feee5e731ffe73927e3d/apparmor.d/groups/gvfs/gvfs-udisks2-volume-monitor#L71-L73

https://github.com/roddhjav/apparmor.d/blob/789e1ddf8bdb0ae13ec1feee5e731ffe73927e3d/apparmor.d/groups/gnome/gnome-shell-hotplug-sniffer#L17-L18

**Comment by roddhjav** [comment]
Can you try without the `owner`?

**Comment by vbauerster** [comment]
I did, and looks like it helped, at least there are no such messages anymore after inserting usb flash drives.

**Comment by roddhjav** [comment]
Thanks. I will add the change in the profiles

**Comment by vbauerster** [comment]
Also, when invoking `mount` with `--mkdir` following message appears:

```
ALLOWED mount mkdir /mnt/data/ comm=mount requested_mask=c denied_mask=c class=file
```
