### ISSUE TITLE
2 profiles for journalctl?

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#169]
When I executed `aa-logprof` I got the error message:

```
ERROR: Conflicting profiles for journalctl defined in two files:
- /etc/apparmor.d/systemd-journalctl
- /etc/apparmor.d/journalctl
```
And indeed - those 2 profiles are identical with the exception that the `journalctl` profile contains the `attach_disconnected` flag.  The latter has also the line:

`include if exists <local/systemd-journalctl>`

I assume that having those 2 (nearly) identical profiles is an oversight.

**Comment by roddhjav** [comment]
`systemd-journalctl` is not part apparmor.d anymore. It might have been renamed `journalctl`. So just remove it.

**Comment by curiosityseeker** [comment]
Hm, but it still exists here: https://github.com/roddhjav/apparmor.d/blob/main/apparmor.d/groups/systemd/systemd-journald

**Comment by curiosityseeker** [comment]
Thanks.
