### ISSUE TITLE
`make full` doesn't contain ignored profiles

### ISSUE THREAD

**Issue by 05storm26** [roddhjav/apparmor.d#173]
According to `dists/ignore/main.ignore`, when you run `make full` should contain all the profiles. But it doesn't.

The discord profile is missing even if you run `make full` instead of `make`

**Comment by roddhjav** [comment]
`make full` does not include all profiles. It includes the profile required for [full system confinement](https://apparmor.pujol.io/development/structure/#full-system-policy) (so `init` and `systemd`). It is still in dev and should not be used outside a test VM.
