### ISSUE TITLE
Discord profile wrong executable path/libdir on arch linux

### ISSUE THREAD

**Issue by 05storm26** [roddhjav/apparmor.d#174]
In the Discord profile the libdir path should also contain `/opt/discord/` as a libdir since on Arch linux the arch `discord` package installs the app to `/opt/discord`. (The executable path is thus: `/opt/discord/Discord`)

**Comment by roddhjav** [comment]
That should be fixed now.

**Comment by roddhjav** [comment]
Thanks. That should be fixed now.
