### ISSUE TITLE
Errors parsing gnome profiles and unable to acess gdm

### ISSUE THREAD

**Issue by giovanniPepi** [roddhjav/apparmor.d#176]
Enabling all profiles leave the system unable to acess gdm after booting:

Jun 28 08:03:31 archlinux apparmor.systemd[455]: AppArmor parser error for /etc/apparmor.d in profile /etc/apparmor.d/colord at line 26: keyword "in" is not allowed in dbus rules
Jun 28 08:03:31 archlinux apparmor.systemd[662]: AppArmor parser error for /etc/apparmor.d in profile /etc/apparmor.d/gnome-session-binary at line 38: keyword "in" is not allowed in dbus rules
Jun 28 08:03:31 archlinux apparmor.systemd[664]: AppArmor parser error for /etc/apparmor.d in profile /etc/apparmor.d/gnome-shell at line 72: keyword "in" is not allowed in dbus rules

line 38 in gnome-session binary seems ok:

  dbus (receive send) bus=session path=/org/gnome/SessionManager{,/**} interface=org.freedesktop.DBus.Properties member={GetAll,PropertiesChanged} peer=(name="{org.freedesktop.DBus,:*}", label={gsd-*,gnome-*,xdg-desktop-portal-*}),

**Comment by roddhjav** [comment]
Hi,

The logs you provided are only Apparmor parser error on profile compilation. This is something you can detect during the installation of apparmor.d (or by doing `systemctl restart apparmor`). As the profile are known to compile without issues, the problem might come from another profiles in your `/etc/apparmor.d`

You did not provided Apparmor logs (from `aa-log` or `/var/log/audit/audit.log`), however from the compilation error we can guess that all other profiles (including `gdm`) compiled successfully and were enabled on boot, as a few gnome profiles were missing, gdm was not able to transition to these profile and apparmor blocked gdm.
