### ISSUE TITLE
Artix Support?

### ISSUE THREAD

**Issue by cmpi66** [roddhjav/apparmor.d#179]
Any way to get artix Linux support?

**Comment by roddhjav** [comment]
Artix is arch based. So you can simply install the pkg for arch and it should work.

However, as Artix does not have systemd it may or may not raise issue...

**Comment by cmpi66** [comment]
Hey thanks for the quick reply, I tried installing it from the AUR, but the makefile fails, it says artix is not one of the supported distros.

**Comment by roddhjav** [comment]
I updated the PKGBUILD on the AUR to force archlinux build, so now it should work.

**Comment by cmpi66** [comment]
Thanks so much, it worked.
