### ISSUE TITLE
openSUSE: build with dummy-release fails

### ISSUE THREAD

**Issue by cboltz** [roddhjav/apparmor.d#180]
apparmor.d checks /etc/os-release during build, and aborts if it finds an unknown distribution.

When building for Tumbleweed, the check works when you really build for Tumbleweed (the released packages).

However, the build fails if you build for Factory (which is the future Tumbleweed, after it passes openQA).

The difference is that Factory contains a `dummy-release` package, which is preferred over the `openSUSE-release` package because it avoids superfluous rebuilds (opensuse-release gets rebuilt for every Tumbleweed snapshot).

It would be nice to also allow building apparmor.d with dummy-release. See https://build.opensuse.org/package/view_file/openSUSE:Factory/dummy-release/dummy-release.spec (starting at line 44) for the `/etc/os-release` content this package contains.

**Comment by cboltz** [comment]
I forgot to include the actual error message:

    [  194s] [1;31m ✗ Error: [0msuse is not a supported distribution

**Comment by roddhjav** [comment]
**Short:** Right now, you can set `DISTRIBUTION=opensuse` and it will bypass reading from `/etc/os-release`.

**Long:** Currently the build program is looking for an id it knows in `ID` or `ID_LIKE`, ie: https://github.com/roddhjav/apparmor.d/blob/c6a048c9cad0e48f9c237e52d77eef568a846d67/pkg/prebuild/tools.go#L17

Then, this ID is used to set special config by the prebuild tool as well as special flags and ignore file `<dist>.flags`, `<dist>.ignore`.

So I can simply add `suse` to this list. However, I did it this way to easily catch all distribution based on the major one (I was tired of adding a new one for each archlinux based dists)
