### ISSUE TITLE
Missing "startplasma-wayland" profile, but "sddm" tries to transition to it.

### ISSUE THREAD

**Issue by PhysicsIsAwesome** [roddhjav/apparmor.d#188]
Hi,

the sddm profile has the following line:
> @{bin}/startplasma-wayland  rPx,
https://github.com/roddhjav/apparmor.d/blob/4894d6a3c44b6fbfa5f19d844093335b70321a1e/apparmor.d/groups/kde/sddm#L68

Because the startplasma-wayland profile doesn't exist, the transition fails and you can't login to a Wayland session on KDE even if sddm is in complain mode.

Tested on EndeavourOS (Arch) with aur/apparmor.d-git version 0.1342-1.

Best regards,
PhysicsIsAwesome

**Comment by roddhjav** [comment]
Should be fixed for now. The actual profile is still in dev, the fix allow to start the program unconfined.
