### ISSUE TITLE
systemd-udevd is unconfined

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#199]
I just noticed that systemd-udevd is unconfined on my Arch system. 

`aa-status` does **not** report that that profile is in complain mode (as it should), and `ps auxZ` reports:

`138: unconfined                      root         327  0.0  0.0  36440 11580 ?        Ss   14:01   0:00 /usr/lib/systemd/systemd-udevd`

**Comment by roddhjav** [comment]
This is on purpose, as the current version of the profile is known to break the system (depending of the hardware you have). See #60 if you still want to enable it. Feedback is welcome if you find any issue...

**Comment by curiosityseeker** [comment]
Oops - sorry, I missed that :(

I might try it and report.
