### ISSUE TITLE
typo: tunnables instead of tunables in include directive

### ISSUE THREAD

**Issue by glitsj16** [roddhjav/apparmor.d#202]
Thank you for this awesome project. After playing around a bit to familiarize with configuration I noticed there's a typo in https://github.com/roddhjav/apparmor.d/blob/b2fa7bacb8e4a71cdd1aab97bbf2e70626a5257a/apparmor.d/tunables/xdg-user-dirs.d/apparmor.d#L24

I didn't open a PR for correcting `tunnables` in the referenced file. But if you want me to, feel free to ping.

**Comment by roddhjav** [comment]
Nice catch, thanks. feel free to open a PR to fix it.
