### ISSUE TITLE
build output: ‼ Profile ctop not found

### ISSUE THREAD

**Issue by glitsj16** [roddhjav/apparmor.d#203]
I started to do git builds on my Arch Linux machine and noticed some warnings are thrown:

```
[...]
Building apparmor.d profiles for arch.
 ✓ Initialize a new clean apparmor.d build directory
 ✓ Ignore profiles/files in dists/ignore/main.ignore
 ✓ Ignore profiles/files in dists/ignore/arch.ignore
 ✓ Merge all profiles
 ‼ Profile atril-previewer not found
 ‼ Profile ctop not found
 ‼ Profile DiscoverNotifier not found
 ‼ Profile epiphany-webapp-provider not found
 ‼ Profile kiod5 not found
 ‼ Profile man not found
 ‼ Profile plasma-discover not found
 ‼ Profile steam not found
 ‼ Profile steam-fossilize not found
 ‼ Profile steam-game not found
 ‼ Profile steam-gameoverlayui not found
 ‼ Profile steam-reaper not found
 ‼ Profile systemsettings not found
 ✓ Set profile flags from dists/flags/main.flags
 ✓ Set profile flags from dists/flags/arch.flags
 ✓ Builded profiles with:
 ⋅ Bypass userspace tools restriction
 ⋅ Set complain flag on all profiles
[...]
```

Nothing breaks, and for most of these I've found a reasonable explanation in the ignore files. The exception is `ctop`, for which I'm only finding this single reference in the repo:

https://github.com/roddhjav/apparmor.d/blob/b2fa7bacb8e4a71cdd1aab97bbf2e70626a5257a/dists/flags/main.flags#L52

Could this be an emission?

**Comment by roddhjav** [comment]
This is on purpose. This warning is just an indication to (myself to) keep the `dists/ignore/*.ignore` more or less clean.
It warns that some profiles with flags defined are not present in the final project either because they are explicitly ignored, or  because they have not been published yet.

**Comment by glitsj16** [comment]
Good to know. Thanks for explaining!
