### ISSUE TITLE
How to overcome the limit for profile transitions?

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#206]
I remember that I had read somewhere that in AppArmor currently the number of allowed profile transitions per profile is limited to 20 (unfortunately I couldn't find the source in a trice). And exactly that problem occurs for me for the `plasmashell` profile: It includes the `app-launcher-user` abstraction but I have the need to add some more applications via rPx or rix in order to avoid `plasmashell//null-/ ...` errors in `aa-log`. 

Unfortunately, regardless if I add them to `local/plasmashell ` or to `abstractions/app-launcher-user.d/complete` I always get the error message:

`Profile plasmashell has too many specified profile transitions.`

and the profile fails to load. And the worst aspect is that profiles which I have even in enforce mode are no longer properly confined:

```
/usr/lib/libreoffice/program/oosplash (318390) plasmashell//null-/usr/lib/libreoffice/program/soffice//null-/usr/lib/libreoffice/program/oosplash
/usr/lib/libreoffice/program/soffice.bin (318432) plasmashell//null-/usr/lib/libreoffice/program/soffice//null-/usr/lib/libreoffice/program/oosplash//null-/usr/lib/libreoffice/program/soffice.bin
```

So is there a trick how to overcome this limitation?

**Comment by curiosityseeker** [comment]
Okay, [here](https://lists.ubuntu.com/archives/apparmor/2019-October/012050.html) is the statement I was referring to. So it was actually 12 transitions, and I don't know if that patch that raises the limit to 28 has landed in the meantime.

**Comment by roddhjav** [comment]
There is no real solution. We just need to wait for upstream to increase this. 
The only workaround would be to use more glob when possible and limit our use of `->`.

**Comment by curiosityseeker** [comment]
Okay, thanks.
