### ISSUE TITLE
udisk trouble in artix

### ISSUE THREAD

**Issue by osevan** [roddhjav/apparmor.d#216]
Udisk makes trouble, when usb stick plugged in

Os= artix linux.

Every profile are in complain mode

defuse.ca/b/D6cYGUXw

**Comment by osevan** [comment]
Could you tell us how to fix self? 

Becauese normaly , aa-logprof do the questions for us and we can tell allow or not. 
But this time even when allowed via aa-logprof and same time in complain mode nothing do it better.

Thanks and

Best regards

**Comment by osevan** [comment]
I think aa-log -r spits out rules of log file

**Comment by roddhjav** [comment]
I fixed one of the issue. I guess that your system (DE, init...) is using `dbus-daemon-launch-helper` to start these programs.

Also, you will need to enable the `dbus-daemon` profile again as it is required by other:
```
ALLOWED at-spi-bus-launcher exec @{bin}/dbus-daemon -> @{bin}/dbus-daemon info="profile transition not found" comm=at-spi-bus-laun requested_mask=x denied_mask=x error=-13
```

This will prevent  `dbus-daemon`  to start (even in complain mode) (it can also explain why aa-logprof was lost)

(I ignored the profiles not present in this project)

**Comment by osevan** [comment]
Works like a charme after edited and  sudo apparmor_parser -r dbus-daemon...


But why aa-logprof couldnt fix this? 
Thx and

Best regards.

**Comment by roddhjav** [comment]
I guess, it simply cannot propose to transition to a profile that does not exist. 

Also, this is the kind of special errors that can break a program even in complain mode. See the `info` section of https://apparmor.pujol.io/issues/#known-issues
