### ISSUE TITLE
badwolf browser cant start

### ISSUE THREAD

**Issue by osevan** [roddhjav/apparmor.d#217]
defuse.ca/b/GEsrejvD
Even my firejail-default profile cant shown in aa-status.  Something wrong. 

https://github.com/netblue30/firejail/blob/master/etc/apparmor/firejail-default
Thanks and

Best regards

**Comment by roddhjav** [comment]
This has nothing to do with this project. As this profile is not part of `apparmor.d`, I don't know if it is your own profile or through firejail. I am afraid I can't help you here.

Note: from the log, the badwolf needs the `attach_disconnected` flag.

**Comment by osevan** [comment]
Ok badwolf profile fixed.

Firejail profile fixed too

Big thx and amazing project. 

Dont forget firejail project is additional security layer working with apparmor lsm hand in hand
