### ISSUE TITLE
new log files from cachyos

### ISSUE THREAD

**Issue by osevan** [roddhjav/apparmor.d#220]
At the Moment everything in complain mode

Os= cachyos

https://paste.cachyos.org/p/aa77d37

**Comment by roddhjav** [comment]
There is already a PR for this and it should be integrated soon. For now, just add  `@{bin}/kstart rPUx,` in kglobalaccel5

**Comment by osevan** [comment]
Please update here close this issi'ue when pull request is done.

**Comment by osevan** [comment]
Pr is already done?

**Comment by roddhjav** [comment]
It is now, beware, the kstart profile is still a wip (PR welcome) it may lead to issue (even in complain mode).
