### ISSUE TITLE
fc-cache: @{exec_path] is not resolved

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#222]
The [fc-cache profile](https://github.com/roddhjav/apparmor.d/blob/main/apparmor.d/groups/freedesktop/fc-cache) looks like this:

```
@{exec_path} = /{snap/snapd/@{int}/,}{usr/,}bin/fc-cache{,-32,-v*}
profile fc-cache @{exec_path} {
```

However, once installed on my system I get:
```
@{exec_path} = /{snap/snapd/@{int}/,}{usr/,}bin/fc-cache{,-32,-v*}
profile fc-cache  {
```
and I got an error regarding the `pacman` profile where fc-cache is called via rPx. The @{exec_path} is obviously not resolved.

Hm, why is that?

**Comment by roddhjav** [comment]
Thanks a lot for this catch. It explained a few issue I have... I need to deploy a more sustainable fix to prevent this to happen again.
