### ISSUE TITLE
apparmor + plasma plasmoid/plasmoid

### ISSUE THREAD

**Issue by Cherkah** [roddhjav/apparmor.d#226]
hi
i've installed an kde applet which works nice without apparmor.d.
As it is an kde applet there is no profile for it.
 So as to get more info about this applet take a look  at this  link [eventcalendar](https://github.com/kanocz/plasma-applet-eventcalendar)

technicaly  that is what i get :
```
...
qml: [eventcalendar] OpenWeatherMap.fetchDailyWeatherForecast.err HTTP Error 0 0
qml: [eventcalendar] OpenWeatherMap.fetchDailyWeatherForecast.err HTTP Error 0 0 null
...
org.kde.plasma.containmentlayoutmanager: Error: cannot change the containment to AppletsLayout
org.kde.plasma.containmentlayoutmanager: Error: cannot change the containment to AppletsLayout
...
file:///home/MyNameBi/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/calendars/GoogleTasksManager.qml:117: ReferenceError: handleError is not defined
```
thanks

**Comment by roddhjav** [comment]
Can you provide the apparmor log you got (`aa-log -R`). See https://apparmor.pujol.io/report/
