### ISSUE TITLE
aa-status doesn't prints already running apps as enforced  even when they are activated .

### ISSUE THREAD

**Issue by osevan** [roddhjav/apparmor.d#228]
Hey roddhjav,

I figured out next bug with profile firejail-default.

On systems without your profiles,  applications started with firejail and apparmor enabled at compile level  plus applications started with apparmor flag inside firejails buildin profile , i can see in aa-status my enforced application as firejail-default active.

The same not working on systems with your profiles in complain mode.

Im running in my test lab  everything  in complain mode and allow only firejail-default in enforce mode,  but even app started inside firejail successfully , aa-status doesnt prints functionality. 

No sandboxed applications listing inside enforced list of aa-status output. 

:-(

Thanks and
Best regards

**Comment by curiosityseeker** [comment]
I'm not quite sure that I fully understand what you're saying - but:

1. If you think there is a problem with `aa-status` it's not a problem with this project but a problem which you should report to [upstream](https://gitlab.com/apparmor/apparmor/-/issues).
2. You're obviously sandboxing your apps with Firejail. Note that in this case the `firejail-default` profile is **always** and **exclusively (!!!)** used. E.g., if you sandbox Firefox with Firejail, it **only** uses the `firejail-default` profile and **not** the `firefox` profile. This is why it doesn't appear in the `aa-status` output. If you really want to use the `firefox` AppArmor profile instead you should add `ignore apparmor` to your `firefox.local` profile in `~/.config/firejail`.  This make sure that Firefox is both sandboxed by Firejail and confined by the application-specific AppArmor profile. I suggest that you also add 

`include <abstractions/base.d/firejail-base>`

to `/etc/apparmor.d/local/firefox` as this [improves](https://github.com/netblue30/firejail/blob/master/etc/apparmor/firejail-base) the compatibility of Firejail with AppArmor. This is what I've been doing for a long time.

**Comment by osevan** [comment]
No, when i enforce on other machine firejail-default - prefered Apparmor profile by me for fj sandboxing - and starting with apparmor flag,  everything is great inside aa-status.


But when i acrivate everything in complain mode this machine with this project, and enforce firejail-default and make sure Apparmor flag inside profile,  than nothing about firejail-default spits out inside aa-status. 


This is the reason why im asking which version of apparmor pkg i should install for arch?

**Comment by curiosityseeker** [comment]
I think you're misunderstanding several aspects here:

1. On Arch Linux there is the `apparmor` package which contains the apparmor userspace tools **and** about 50 profiles provided by upstream - which means that you're using those profiles anyway once you install the `apparmor` package. (If I remember correctly, it's different on Debian or Ubuntu where specific `apparmor-profiles` and `apparmor-profiles-extra` packages are available.)
2. The profiles from upstream do **not overlap** with the many profiles from the apparmor.d project which [cover](https://github.com/roddhjav/apparmor.d#concepts) the core applications on your system. These profiles confine most services, your desktop environment and many other core applications like browsers (although many profiles are still in `complain` mode as this project is still a WIP). Hence, your question "which version of apparmor pkg i should install for arch?" makes no sense: Again, you have the profiles from upstream installed on your system anyhow by installing the `apparmor` package - so the only relevant question is if you should install the profiles from the apparmor.d project **in addition to** the profiles from upstream. That's something you have to decide. I would say you should.
3. If it comes to Firejail, it sandboxes a lot of applications (way more than this project) and not really system services or your desktop environment. As already mentioned in my previous reply: all applications which are sandboxed by Firejail **and** have an apparmor.d profile **only** use `/etc/apparmor.d/firejail-default`. That's what you're seeing in the `aa-status` output. If you don't want that you have to follow the steps outlined earlier.

**Comment by osevan** [comment]
I love firejail project like i do this flr your project amd want use both. 

My complaining is, why aa-status doesn't spit out application usage of firejail-default profile. 

BUT i will show some logs too

**Comment by osevan** [comment]
Here one picture. 


Even i did sudo aa-enforce firejail-default 
![IMG_20231027_164335](https://github.com/roddhjav/apparmor.d/assets/77795961/c7fca450-ec12-4d7b-b6dd-a3c679711cba)

**Comment by osevan** [comment]
paste.cachyos.oeg/p/a1b7cb6/

**Comment by curiosityseeker** [comment]
> Even i did sudo aa-enforce firejail-default !

This only works if you're in the `/etc/apparmor.d` directory. If you're not you have to execute:

`sudo aa-enforce /etc/apparmor.d/firejail-default`

**Comment by roddhjav** [comment]
You need to update your profiles, we have made update to the profiles since last time you pulled them, most of this issue should be fixed already.

**Comment by osevan** [comment]
Ok, my last updates was 2 month ago.

**Comment by osevan** [comment]
After update i can see apparmor is working 

But not inside aa-status.
Anyway for me is fixed.

If i have something wrong i will open again
