### ISSUE TITLE
Automatically installing dependency profiles when installing profiles seperately

### ISSUE THREAD

**Issue by monsieuremre** [roddhjav/apparmor.d#234]
I have successfully created a shell script that installs all the dependency profiles with the targeted profile we want to install. This function recursively pulls the dependency profiles of those profiles too. Before recursion, the script checks if the profile is already present to prevent infinite loops. This pulls all dependencies. One of the harder things was to get regex stuff work with this as well. Like profiles ```wl-{copy,paste}``` or ```mount.*```. These work too. This implementation covers everything I can see. This is however implemented as a shell function. I am going to create a pull with this but first I want to know if what I want is compatible with the project. I don't want a modified makefile. I am going to add a standalone shell script that users can use to install profiles. This can be called inside the makefile if desired. This is the function:

```
BUILD=.build
DESTDIR=/

install_seperate_with_depends() {
	for profile in "$@"
	do
		cp $BUILD/apparmor.d/$profile $DESTDIR/etc/apparmor.d/$profile
		grep "rPx," "$BUILD/apparmor.d/$profile" | while read l1
		do
			dep=$(echo "$l1" | awk '{print $1}')
		   	dep=$(echo $dep | awk -F"/" '{print $NF}')
			find . -type f  -name $dep | while read l2
		    	do
				if [ ! -f "$DESTDIR/etc/apparmor.d/$dep" ]; then
					install_seperate_with_depends $dep
				fi
		    	done
		done
		grep "rPx -> " $BUILD/apparmor.d/$profile | while read l1
		do
			dep=$(echo $l1 | awk '{print $NF}' | awk '{if (NR!=1) {print substr($2, 1, length($2)-1)}}')
			find . -type f  -name $dep | while read l2
			do
			    if [ ! -f "$DESTDIR/etc/apparmor.d/$dep" ]; then
				install_seperate_with_depends $dep
			    fi
			done
		done
	done
}
```
For example ```install_seperate_with_depends aa-teardown``` installs the profiles ```aa-teardown```, ```apparmor.systemd```, ```apparmor_parser``` and ```systemd-detect-virt```. Is the maintainer ok with the idea that this is going to be a standalone script and not implemented within the makefile? If anyone is willing to port this into the makefile, I am ok with it, please post your solution as an answer. But I find this rather complicated regex functionality cascading better take place in a seperate script for simplicity and maintainability.

**Comment by roddhjav** [comment]
This is really nice, thanks a lot. I am perfeclty fine with a script (there are already a few). Put your script in `dists/partial.sh`, have a look at similar scripts like `dists/build.sh` and `dists/docker.sh` to see the structure. Then, use it in the makefile as follow: 
```make
$(P):
	# ... install aa-log, abs, tunable as already present ...
	@bash dists/partial.sh ${@}
	@systemctl restart ....
```

**Comment by monsieuremre** [comment]
Ok I am going to create a pull with the script.

**Comment by roddhjav** [comment]
The current solution (https://apparmor.pujol.io/install/#partial) will overwrite any previous files. It is also why installing with a package manager is preferred.
