### ISSUE TITLE
ntfs usb stick cant mount even module is loaded

### ISSUE THREAD

**Issue by osevan** [roddhjav/apparmor.d#237]
Any other stick without ntfs working
Only ntfs formatted sticks can't mountable. 

https://paste.cachyos.org/p/a1b7cb6/
https://paste.cachyos.org/p/9db5cac

**Comment by curiosityseeker** [comment]
Please do not use sceenshots. Use the output of `aa-log -R` instead.

**Comment by osevan** [comment]
Here is freshly updated system with fresh logs

ntfs-3g is already installed and module is loaded

defuse.ca/b/5HaoyIlt

**Comment by roddhjav** [comment]
Thanks, these logs would be useful. Although I am not 100% sure they are related to `ntfs-3g`.
