### ISSUE TITLE
profile request for betterbird

### ISSUE THREAD

**Issue by osevan** [roddhjav/apparmor.d#253]
Betterbird is Thunderbird fork with faster patches.

Thanks and

Best regards

**Comment by roddhjav** [comment]
As betterbird is pretty much thunderbird, if you add `betterbird` here: https://github.com/roddhjav/apparmor.d/blob/fe0cb4b48dbbf1dfa962a9a6c0bb4020be66996c/apparmor.d/profiles-s-z/thunderbird#L10

You should be able to confine betterbird using the thunderbird profile.
