### ISSUE TITLE
not able to mount partition/subvolume

### ISSUE THREAD

**Issue by Jeff-WuYo** [roddhjav/apparmor.d#259]
My problem is weird, and I couldn't figure out what was happening. \
I'm on archlinux. I try to mount a partition while I'm using qtile under xorg (start by xinit). I keep getting error message.
```
doas mount -o rw,subvolid=5,noatime /dev/nvme2n1p3 /mnt
mount: /mnt: filesystem was mounted, but any subsequent operation failed: Operation not permitted.
```
BUT, it works fine under any tty session. It mounted as expected. It also work after I `aa-teardown` everything, even I `systemctl reload apparmor.service` \
I've check the log, couldn't find any word **DENIED**. The problem doesn't exist under arch stock apparmor comfig. I've tried `aa-complain /etc/apparmor.d/*`, the problem still remain. I also have similar issue with bwrap while launch steam game (I'll file another issue.). \
from journalctl. The successfully mount and errored mount look the same in journal.
```
Dec 05 01:53:03 arch-z490-g dbus-daemon[1947]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.21586' (uid=0 pid=96064 comm="doas mount -o rw,subvolid=5,noatime /dev/nvme2n1p3")
Dec 05 01:53:03 arch-z490-g dbus-daemon[1947]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.home1.service': Unit dbus-org.freedesktop.home1.service not found.
Dec 05 01:53:03 arch-z490-g doas[96064]: pam_unix(doas:session): session opened for user root(uid=0) by jeff(uid=1259)
Dec 05 01:53:03 arch-z490-g doas[96065]: jeff ran command mount -o rw,subvolid=5,noatime /dev/nvme2n1p3 /mnt as root from /home/jeff/Downloads/apparmor.d-log
Dec 05 01:53:03 arch-z490-g doas[96064]: pam_unix(doas:session): session closed for user root
```
[Here are the logs.](https://pastebin.com/EuMqAhZD)

**Comment by Jeff-WuYo** [comment]
Thanks for the update, it works as expected. The bwrap steam game issue mentioned is bypassed too. \ 
I don't have enough knowledge to create a dedicated profile, might try to create a profile in the future. I think I can close the issue for now.

**Comment by Jeff-WuYo** [comment]
I currently install the profiles from AUR. Don't know how to do it from AUR helper of it's git directory, I guess I have to git clone directly from here if I want to test it out.

**Comment by roddhjav** [comment]
Instead of getting the package from the AUR, install it from this repository:
```sh
git clone https://github.com/roddhjav/apparmor.d.git
cd apparmor.d.
# edit the dists/ignore/main.ignore  
makepkg -si
```
