### ISSUE TITLE
ibus not starting under qtile

### ISSUE THREAD

**Issue by Jeff-WuYo** [roddhjav/apparmor.d#260]
After recent #259 issue, and answered in [this comment](https://github.com/roddhjav/apparmor.d/issues/259#issuecomment-1839422249), the issue was bypassed. However, a new issue appear.\
Before the 7f81da3a719f453b673dadff9733fc861a1df646 update, I was able to start ibus-daemon by placing `ibus-daemon -rxRd` in `.xinitrc`. After the update, ibus-daemon failed to start. There's no difference before and after in the journal.
```
at-spi-bus-launcher[2386]: dbus-daemon[2386]: Activating service name='org.a11y.atspi.Registry' requested by ':1.4' (uid=1259 pid=109922 comm="/usr/lib/polkit-gnome/polkit-gnome-authentication-")
at-spi-bus-launcher[2386]: dbus-daemon[2386]: Successfully activated service 'org.a11y.atspi.Registry'
at-spi-bus-launcher[109938]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
```
There's a relative line in aa-log, end with an error.
```
ALLOWED ibus-daemon exec @{lib}/ibus/ibus-ui-gtk3 -> @{lib}/ibus/ibus-ui-gtk3 info="profile transition not found" comm=ibus-daemon requested_mask=x denied_mask=x error=-13
```
The full aa-log is at [Here](https://pastebin.com/02dZ265N)

**Comment by roddhjav** [comment]
Good cacth. Should be fixed now. `ibus-ui-gtk3` will simply be run unconfined.
