### ISSUE TITLE
fcitx5 not working porperly when start using xinit

### ISSUE THREAD

**Issue by Jeff-WuYo** [roddhjav/apparmor.d#263]
I'm on Archlinux, using Qtile with xinit. `fcitx5` does start using xinit, but `fcitx5-configtool`, `fcitx5-gtk`, `fcitx5-qt` can't interact with `fcitx5`. I'm not able to use fcitx5 on Qt nor GTK. However, if I start `fcitx5` manually after I started xorg, fcitx5 works as intended. If I `aa-teardown`, I'm able to start fcitx5 using xinit. It's similar to #260 at some extent. \
Like #259 , I wasn't able to find a relevant log, but here's some logs anyway.
```
ALLOWED xorg capable comm=Xorg capname=net_admin capability=12
ALLOWED xorg open /tmp/server-0.xkm comm=Xorg requested_mask=r denied_mask=r
ALLOWED xorg unlink /tmp/server-0.xkm comm=Xorg requested_mask=d denied_mask=d
ALLOWED xorg open owner /dev/input/mouse0 comm=Xorg requested_mask=wr denied_mask=wr
ALLOWED xorg open owner /dev/input/mouse1 comm=Xorg requested_mask=wr denied_mask=wr
ALLOWED xinit open owner @{HOME}/.xinitrc comm=sh requested_mask=r denied_mask=r
ALLOWED xorg capable info="optional: no audit" comm=Xorg capability=34 capname=syslog error=-1
```

**Comment by roddhjav** [comment]
Hey, these logs does not seems to be fully related. Do you have more logs ?

**Comment by Jeff-WuYo** [comment]
I rebooted, try to get a cleaner [log](https://pastebin.com/WmR5dE19).
