### ISSUE TITLE
Issue with GPG

### ISSUE THREAD

**Issue by idotek** [roddhjav/apparmor.d#265]
Hi everyone,

I tried to add the docker gpg key in enforce mode, but aa-log returned this error:

DENIED gpg mknod owner /etc/apt/keyrings/docker.gpg comm=gpg requested_mask=c denied_mask=c

I've added these two lines to /etc/apparmor.d/gpg:

  owner /etc/apt/keyrings/ rw,
  owner /etc/apt/keyrings/** rwkl -> /etc/apt/keyrings/**,

It works, but I'm no expert, so maybe there's a better way.

Have a good day and thanks for this amazing projet!

**Comment by roddhjav** [comment]
Good catch, thanks. It should be fixed now.
