### ISSUE TITLE
RPM packaging

### ISSUE THREAD

**Issue by monsieuremre** [roddhjav/apparmor.d#267]
So there is a debian target and we can build the .deb package the normal way, very cool and nice. For openSUSE tumbleweed, you can do the manual installation with the makefile, which is a ok i guess, but not as good as an rpm file. You mention the repository of Christian Boltz who has the rpm package available. Well ok, but I want to build it myself. The package is not from you, the developer, it is from a third party. There should at the very least be a way to build the rpm package. It isn't more difficult than having a deb target. There needs to be a spec file defined only and the target can also be defined in the makefile too, for ease. Like calling make rpm directly would be possible that way, tho this is optional. Since Mr. Boltz already packages this project as rpm, there is a spec file suited for this repostiory already. I think you should look into porting this functionality into the project itself. I think this should not require much new work since it already exists somewhere. I would like to build the rpm with ease directly after cloning this repo locally.

**Comment by roddhjav** [comment]
You are perfectly right... but that already exist. The specs file is in `dists/apparmor.d.spec`. And `make rpm` already exist and will build and install the package from the current source files.

**Comment by monsieuremre** [comment]
I am sorry I was unaware of this. The only information and instruction on your [website](https://apparmor.pujol.io/install.html) only mentions boltz's repository and does not mention to possibility to build an rpm target. Whie under debian, the build instructions for the deb target are given. This is why I was under the wrong impression that building an rpm wasn't possible. It is a mistake on my end that I did not check this manually before opening the issue.

You might consider adding this information to your website under suse instructions. Because it gives the impression that there is no way to build an rpm target manually.

**Comment by roddhjav** [comment]
You are right, although the rpm target is only for development, so I may add it in the dev section.
