### ISSUE TITLE
aa-log -s  yields "read .: is a directory"

### ISSUE THREAD

**Issue by mbwgh** [roddhjav/apparmor.d#268]
I have installed apparmor.d via the corresponding [AUR package](https://aur.archlinux.org/packages/apparmor.d-git) and it appears apparmor is running in complain mode as intended.

The output of `sudo journalctl -b --no-pager | tail` looks like:
```
Dec 26 19:37:29 legion kernel: audit: type=1400 audit(1703615849.025:1388628): apparmor="ALLOWED" operation="getattr" class="file" profile="dhcpcd//null-/usr/bin/resolvconf" name="/etc/ld.so.cache" pid=9829 comm="resolvconf" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Dec 26 19:37:29 legion kernel: audit: type=1400 audit(1703615849.025:1388629): apparmor="ALLOWED" operation="open" class="file" profile="dhcpcd//null-/usr/bin/resolvconf" name="/usr/lib/libreadline.so.8.2" pid=9829 comm="resolvconf" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Dec 26 19:37:29 legion kernel: audit: type=1400 audit(1703615849.025:1388630): apparmor="ALLOWED" operation="getattr" class="file" profile="dhcpcd//null-/usr/bin/resolvconf" name="/usr/lib/libreadline.so.8.2" pid=9829 comm="resolvconf" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Dec 26 19:37:29 legion kernel: audit: type=1400 audit(1703615849.025:1388631): apparmor="ALLOWED" operation="file_mmap" class="file" profile="dhcpcd//null-/usr/bin/resolvconf" name="/usr/lib/libreadline.so.8.2" pid=9829 comm="resolvconf" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0
Dec 26 19:37:29 legion kernel: audit: type=1400 audit(1703615849.025:1388632): apparmor="ALLOWED" operation="open" class="file" profile="dhcpcd//null-/usr/bin/resolvconf" name="/usr/lib/libc.so.6" pid=9829 comm="resolvconf" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Dec 26 19:37:29 legion kernel: audit: type=1400 audit(1703615849.025:1388633): apparmor="ALLOWED" operation="getattr" class="file" profile="dhcpcd//null-/usr/bin/resolvconf" name="/usr/lib/libc.so.6" pid=9829 comm="resolvconf" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Dec 26 19:37:29 legion dbus-daemon[1747]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.73' (uid=0 pid=9838 comm="sudo journalctl -b --no-pager")
Dec 26 19:37:29 legion dbus-daemon[1747]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.home1.service': Unit dbus-org.freedesktop.home1.service not found.
Dec 26 19:37:29 legion sudo[9838]:      mbw : TTY=pts/0 ; PWD=/home/mbw ; USER=root ; COMMAND=/usr/bin/journalctl -b --no-pager
Dec 26 19:37:29 legion sudo[9838]: pam_unix(sudo:session): session opened for user root(uid=0) by mbw(uid=1000)
```

If I run `aa-log -s`, I however get `read .: is a directory` with exit code 1. Same if run via sudo.

I don't think this is the intended behavior. Does the problem lie with the way I have installed/ set up apparmor/apparmor.d?

**Comment by mbwgh** [comment]
Ok I noticed a difference in behavior if I enable/start `auditd.service`.

Without auditd running:
  * `(sudo) aa-log`: Empty output
  * `(sudo) aa-log -s`: `read .: is a directory`

With auditd running:
  * `aa-log`: Empty output (exit 0)
  * `sudo aa-log`: Output is produced
  * `aa-log -s`: `read .: is a directory`
  * `sudo aa-log -s`: (After ~30 seconds): `json: cannot unmarshal array into Go struct field systemdLog.MESSAGE of type string`

**Comment by roddhjav** [comment]
`aa-log` is looking for `audit.log` (or `syslog`) logs file. Therefore, on archlinux, auditd need to be installed and started/enabled for aa-log to provide any result. It will only start creating log after it is running too, so initially, the output will be empty (just reboot and you should see some logs). By default you will also need sudo to read the log file).

I am aware of the issue with `aa-log -s` on some system (curiously it works fine on my test VM, regardless of the distribution)
