### ISSUE TITLE
Fish shell support

### ISSUE THREAD

**Issue by hafeoz** [roddhjav/apparmor.d#269]
Fish login shell on Arch Linux doesn't work properly - audit logs will be spammed with complain logs with lines like

```
ALLOWED login//null-/usr/bin/fish//null-/usr/bin/less open /var/log/audit.log requested_mask=r denied_mask=r
```

Adding a `@{bin}/fish rUx` in local override for `login` works for me.

**Comment by chr0m3kanra** [comment]
I can confirm that.
The same measure has fixed the issue for me.

There is a line in the default login profile like:
`@{bin}/{,z,ba,da}sh  rUx,`
Adding the "fi" to the regex would solve this issue.
The resulting line would look like this:
 `@{bin}/{,z,ba,da,fi}sh  rUx,`

**Comment by hafeoz** [comment]
I've compiled a list of common shell binaries we may want to add: #270 

However, [a quick search in the codebase](https://github.com/search?q=repo%3Aroddhjav%2Fapparmor.d+%7B%2Cba%2Cda%7Dsh&type=code) reveals many profiles having a list of shells. I think probably better to have some kind of abstraction (e.g. `abstractions/shell`) rather than using a hard-coded list for each program.

**Comment by chr0m3kanra** [comment]
> I've compiled a list of common shell binaries we may want to add: #270
> 
> However, [a quick search in the codebase](https://github.com/search?q=repo%3Aroddhjav%2Fapparmor.d+%7B%2Cba%2Cda%7Dsh&type=code) reveals many profiles having a list of shells. I think probably better to have some kind of abstraction (e.g. `abstractions/shell`) rather than using a hard-coded list for each program.

I guess that could be a solution but then we would need multiple additional abstractions.
If i'm not mistaken we would need at least one for "inherit execute" `rix,`  like in the profile for sshd and another abstracton for "unconfined execute" `rUx,` like the one in login or sudo.

**Comment by roddhjav** [comment]
The solution is to have a new variable that list all the possible interactive shell. Then it can be used in the profile like: `@{bin}/@{sh} rUx,` or  `@{bin}/@{sh} rix,` depending on the need. I implement this soon
