### ISSUE TITLE
Issue when trying to install mariadb-client & mariadb-server on Deb12

### ISSUE THREAD

**Issue by idotek** [roddhjav/apparmor.d#272]
Hi everyone,

I catch a new DENIED when trying to install mariadb stuff

```
DENIED  apt-extracttemplates mknod owner /var/cache/debconf/tmp.ci/mariadb-server.template.gFqZtp comm=apt-extracttemp requested_mask=c denied_mask=c
DENIED  apt-extracttemplates mknod owner /var/cache/debconf/tmp.ci/mariadb-server.config.ZeyB7u comm=apt-extracttemp requested_mask=c denied_mask=c
DENIED  update-alternatives symlink owner /etc/mysql/my.cnf.dpkg-tmp comm=update-alternat requested_mask=c denied_mask=c
```

So i add in /etc/apparmor.d/apt-extracttemplates:
`owner /var/cache/debconf/** rw,`

And in /etc/apparmor.d/update-alternatives:

`owner /etc/mysql/** rw,`

It works, but I'm no expert, so maybe there's a better way.

Have a good day and thanks for this amazing projet!

**Comment by roddhjav** [comment]
Thanks, it should be fixed now.
