### ISSUE TITLE
Adjust profiles when building for Kicksecure/Whonix to accomodate hardened malloc usage

### ISSUE THREAD

**Issue by monsieuremre** [roddhjav/apparmor.d#278]
Kicksecure/Whonix already packages hardened malloc as provides it as a package. The reason it is not enabled for everything by default is that some binaries will break with hardened malloc. Ideally, it is best to enable hardened malloc in the environment and exempt the problematic binaries manually. The current method of kicksecure doing this is quite weak and problematic, using bubblewrap and blocking other things in the process. This is why it is to this day still not enabled by default.

I have found and tested a more solid and reliable way of achieving this exemption of binaries. This is what would happen:

* Kicksecure/Whonix enables hardened malloc linking for all binaries as default in the environment.
* Problematic programs are known to us. For these, the corresponding apparmor profiles will include the following line:
```
filter environment LD_PRELOAD contains libhardened_malloc.so,
```
Expected behavior: An application contained with an apparmor profile with this line will not see the value of the environment variable ```LD_PRELOAD```, if the value contains ```libhardened_malloc.so```, and thus will be exempt. Not tested, but I think we can use
```
filter environment LD_PRELOAD contains libhardened_malloc.so, ?????
```
to strip the value of the environment variable of the matching parts. So other portions will still be visible to the binary. Source is an [old wiki page](https://gitlab.com/apparmor/apparmor/-/wikis/EnvironmentVariables), so it might have different syntax now.

My question is, how can the make process add certain lines to certain profiles only if the build target is the whonix deb package? The select files to be affected will be: chromium base abstraction, firefox base abstraction, cryptsetup profile.

Pinging @adrelanos to review the idea too.

**Comment by roddhjav** [comment]
I am not sure I understand what you are trying to do. However, the [filter feature](https://gitlab.com/apparmor/apparmor/-/wikis/EnvironmentVariables) you are referring is not implemented in apparmor yet (and is not planned for apparmor 4).

**Comment by monsieuremre** [comment]
> I am not sure I understand what you are trying to do. However, the [filter feature](https://gitlab.com/apparmor/apparmor/-/wikis/EnvironmentVariables) you are referring is not implemented in apparmor yet (and is not planned for apparmor 4).

It seems you are right. What I am trying to achieve is that I want one environment variable to be visible to some applications with certain profiles and not to other profiles. Is there a way to achieve this currently that you know of? The wiki pages also have stuff like ```deny environment {PATH}``` but it results in a syntax error. So I am not sure how to get this behavior.

**Comment by roddhjav** [comment]
With apparmor, you can't do this. That is more something you will have as part of a sandbox profile (in flatpak for exmple).

**Comment by monsieuremre** [comment]
Na that is the current solution that we want to avoid if possible. Saddening that it isn't possible to this yet.
