### ISSUE TITLE
[Feature] Desktop Entry Specification (Grouping)

### ISSUE THREAD

**Issue by marsianer** [roddhjav/apparmor.d#28]
Is there an easy way to parse the _.desktop_ file for each application?
If yes, we could create a tree based on their categories.

https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

All profiles would be in the same location as in the GNOME / KDE menu.

Examples:
firefox.desktop=Network/WebBrowser
libreoffice-base.desktop=Office/Database
libreoffice-impress.desktop=Office/Presentation
libreoffice-calc.desktop=Office/Spreadsheet
libreoffice-writer.desktop=Office/WordProcessor
kmail2.desktop=Office/Network/Email
gparted.desktop=System/Filesystem

**Comment by roddhjav** [comment]
That would be possible. However, I don't know if it is really useful. Desktop applications are not in scope of this project as they usually should simply be sandboxed (some app can have both). Most of the profiles in group are not desktop apps and therefore would not be covered by this.
