### ISSUE TITLE
Catch for borg backup using S3 backup storage

### ISSUE THREAD

**Issue by idotek** [roddhjav/apparmor.d#280]
I everyone,

I got this new catch using BorgBackup

![image](https://github.com/roddhjav/apparmor.d/assets/25754625/b057f31d-d651-4ebb-b12d-743edbc4a734)

but no idea how to fix it :(

Thanks for your help!

**Comment by nobody43** [comment]
If it really interacts with terminals - it requires `consoles` abstraction:
`  include <abstractions/consoles>`

**Comment by roddhjav** [comment]
Should be fixed now. How do you run borg? Is it inside a sandbox ?
