### ISSUE TITLE
Apparmor option to specify $PWD in profile rules

### ISSUE THREAD

**Issue by vam67423** [roddhjav/apparmor.d#284]
Is there any known way to specify $PWD in apparmor profiles?

I would like to specify a rule that only allows access to the current working directory of the executing process.
Is this possible with apparmor?

Update: 
To clarify, I intent to allow the current working directory at the time of execution.
If appX is executed in /tmp/a it gets access to /tmp/a but cannot change to /tmp/b during its runtime

**Comment by curiosityseeker** [comment]
Perhaps I don‘t understand the problem - but AppArmor is not a blacklisting but basically a whitelisting approach: If you allow access to /tmp/a, access to /tmp/b is forbidden (provided that the profile is in enforce mode, of course).

**Comment by vam67423** [comment]
I would like to make the whitelisted path dependent on the working directory at the time of execution.  
The only way I currently know is to write /tmp/a into the profile, but what I actually want is /tmp/$PWD

The result should be that I can execute the program in an arbitrary path and this path gets whitelisted in apparmor

**Comment by roddhjav** [comment]
No, there is no such feature (that may be a security issue anyway).

The closet thing (that is currently in development in apparmor) is a prompt. Where a rule like:
`prompt owner @{user_download_dirs}/{,**} rw,` means that at the first run of a program, an UI will pop up and ask the user if the access should be allowed or not.

**Comment by vam67423** [comment]
> The closet thing (that is currently in development in apparmor) is a prompt. Where a rule like: `prompt owner @{user_download_dirs}/{,**} rw,` means that at the first run of a program, an UI will pop up and ask the user if the access should be allowed or not.
Thanks for the answer, that may be useful as well
