### ISSUE TITLE
Flatpak / bubblewrap no longer working

### ISSUE THREAD

**Issue by Jeroen0494** [roddhjav/apparmor.d#285]
Hi,

Seems some recent changes to apparmor.d broke support for running flatpaks / anything with bubblewrap:

```
$ flatpak run org.kde.akregator
bwrap: Can't open /proc/self/mountinfo: Permission denied
bwrap: Can't read from privileged_op_socket
error: Failed to sync with dbus proxy
```

[aa-log.txt](https://github.com/roddhjav/apparmor.d/files/14076760/aa-log.txt)

**Comment by roddhjav** [comment]
You need to update the profiles / reboot. The logs clearly show that you did not applied #162.

**Comment by Jeroen0494** [comment]
I don't understand what's going on here. If I look at the profile under /etc/apparmor.d, it still lists the old version:

```
# apparmor.d - Full set of apparmor profiles
# Copyright (C) 2023 Alexandre Pujol <alexandre@pujol.io>
# SPDX-License-Identifier: GPL-2.0-only

abi <abi/3.0>,

include <tunables/global>

@{exec_path} = @{bin}/kglobalaccel5
profile kglobalaccel5 /{,usr/}{,s}bin/kglobalaccel5 flags=(complain) {
  include <abstractions/base>
  include <abstractions/freedesktop.org>
  include <abstractions/qt5>
  include <abstractions/X-strict>

  @{exec_path} mr,

  /usr/share/hwdata/*.ids r,
  /usr/share/icu/@{int}.@{int}/*.dat r,
  /usr/share/kglobalaccel/{,**} r,
  /usr/share/mime/{,**} r,

  /etc/machine-id r,

  owner @{user_config_dirs}/#@{int} rw,
  owner @{user_config_dirs}/kglobalshortcutsrc* rwl,
  owner @{user_config_dirs}/kglobalshortcutsrc.lock rwk,

  @{PROC}/sys/kernel/random/boot_id r,
  @{PROC}/sys/kernel/core_pattern r,

  /dev/tty r,

  include if exists <local/kglobalaccel5>
}
```

But I git pull and update every day to stay up-to-date. For some reason, profiles aren't being updated properly, confusing me into filing stupid bug reports here... Why isn't apt / dpkg updating my profiles? I use the following script:

```
sudo -u jeroen git pull
sudo -u jeroen dpkg-buildpackage -b -d --no-sign
dpkg --install --force-overwrite ../apparmor.d_*_all.deb
systemctl restart apparmor
```

If I remove the kglobalaccel5 profile and install the .deb file, the profile isn't even restored, it's just missing. I have to copy it out of the .deb file to restore it.

**Comment by Jeroen0494** [comment]
Okay, I think I found the problem. Could it be that the file generated was renamed from `all.deb` to `amd64.deb` somewhere around september 17 last year?

**Comment by roddhjav** [comment]
> Okay, I think I found the problem. Could it be that the file generated was renamed from all.deb to amd64.deb somewhere around september 17 last year?

Yes I have done this... long time ago.

**Comment by Jeroen0494** [comment]
Well, let's just say it explains a lot.
