### ISSUE TITLE
What about mentioning `Tested on` systems in profile's header?

### ISSUE THREAD

**Issue by nobodysu** [roddhjav/apparmor.d#29]
We might not commit to whole support in README, but at least mention where this single profile have been tested.
e.g.
`# Tested on: Arch Linux, Debian 11, Ubuntu 20.04, Armbian Bullseye`

**Comment by roddhjav** [comment]
That would require a lot of work. Plus from my experience, the combination of software used matter more than the distribution used. So for instance, in term of AppArmor rules you have more similarities between an Arch and a Debian both on Gnome with Wayland, Pipewire and no Flatpak than with an Arch on Kde, Xorg, Pulseaudio and Flatpak.

**Comment by nobodysu** [comment]
I hope to address my issues some time in the future.
