### ISSUE TITLE
aa-log

### ISSUE THREAD

**Issue by marsianer** [roddhjav/apparmor.d#30]
Is it possible to use aa-log to generate a complete profile?
The official aa-genprof is asking too many questions.

`aa-log -genprof firefox > firefox.profile`

The profile can then be optimized later with a text editor.

**Comment by roddhjav** [comment]
That could be nice to have to initialise a profile. However it is a bit of work. Maybe using, hacking the AppArmor tool would be easier.

**Comment by roddhjav** [comment]
I won't do it. That is too much work to generate profile that need to be mostly rewritten anyway.
