### ISSUE TITLE
build security of dependencies?

### ISSUE THREAD

**Issue by adrelanos** [roddhjav/apparmor.d#305]
As a stopgap for:

* https://github.com/roddhjav/apparmor.d/issues/304

How secure is the process of downloading the dependencies?

* digital signature verification
* hash sum verification

Other options:

* start using embedded code copies?

**Comment by roddhjav** [comment]
There is [hash sum verification](https://github.com/roddhjav/apparmor.d/blob/main/go.sum) as for any go program. It is the supported way of managing build dependencies with go. 

Once I setup proper `dh-golang` Debian packaging, they would be handled via debian packages by adding the following `Build-Depends`:
```
  golang-github-pkg-errors-dev,
  golang-golang-x-exp-dev,
  golang-gopkg-yaml.v3-dev,
  golang-github-arduino-go-paths-helper-dev,
```

> * start using embedded code copies?

That was the old method go had to provide build deps. This is now deprecated.

**Comment by roddhjav** [comment]
I now included/removed all previous build dependencies (golang-golang-x-exp-dev, and golang-github-arduino-go-paths-helper-dev). You should now be able to build without network.
