### ISSUE TITLE
Found reference to variable gdm_local_dirs, but is never declared (gnome-keyring-daemon)

### ISSUE THREAD

**Issue by opticblu** [roddhjav/apparmor.d#306]
Not a big deal, just removed the offending line but:

after an update of 'apparmor.d-git' from the AUR (Arch, 6.8 kernel), apparmor service wouldn't start, journalctl -xeu apparmor service reveals:

Mar 18 01:59:28  apparmor.systemd[205348]: Restarting AppArmor
Mar 18 01:59:28  apparmor.systemd[205348]: Reloading AppArmor profiles
Mar 18 01:59:28  apparmor.systemd[205746]: Found reference to variable gdm_local_dirs, but is never declared
Mar 18 01:59:30  apparmor.systemd[205348]: Error: At least one profile failed to load
Mar 18 01:59:30  systemd[1]: apparmor.service: Control process exited, code=exited, status=1/FAILURE

looks like it's in the gnome-keyring-daemon profile

just bringing it to your attention; I don't use gnome (using hyprland) but gnome-keyring-daemon is installed on my system, which seems relevant;  also, zfs root, almost certainly irrelevant but it's non-standard so fyi

thank you for your work on this project!

**Comment by roddhjav** [comment]
My bad, the main branch is not as stable as I would like it to be (I forgot to push my last commit yesterday...). That should be fixed now.
