### ISSUE TITLE
Mutt child-pager

### ISSUE THREAD

**Issue by doublez13** [roddhjav/apparmor.d#309]
I cherry picked your latest commits and applied them locally (so I'm possibly missing something obvious).

Commit 0619f4d replaced `mutt//pager` with the global `child-pager` profile.

Unfortunately mutt is unable to view mail in the pagers now, as the pagers needs read on `/{var/,}tmp/mutt*`

**Comment by roddhjav** [comment]
Good point. It should be fixed now.
