### ISSUE TITLE
Pacman prints 'error: could not get current working directory'

### ISSUE THREAD

**Issue by 05storm26** [roddhjav/apparmor.d#313]
The issue is caused by some faulty apparmor profile: https://gitlab.archlinux.org/pacman/pacman/-/issues/24#note_92600

Pacman tries to get the current working directory before changing to the root of the filesystem, so it can switch it back to the original working directory. See here: https://gitlab.archlinux.org/pacman/pacman/-/blob/master/src/pacman/conf.c?ref_type=heads#L349

**Comment by roddhjav** [comment]
That is done on purpose.See: https://apparmor.pujol.io/issues/#pacman-could-not-get-current-working-directory

The alternative would have be to give pacman full access to the home directory.
