### ISSUE TITLE
Common DBus rules on Ubuntu?

### ISSUE THREAD

**Issue by nobodysu** [roddhjav/apparmor.d#34]
Following DBus rules are required by many apps:
```
  dbus send
    bus=session
    path=/org/gtk/vfs/mounttracker
    interface=org.gtk.vfs.MountTracker
    member=ListMountableInfo,

  dbus send
    bus=session
    path=/org/gtk/vfs/Daemon
    interface=org.gtk.vfs.Daemon
    member=ListMonitorImplementations,

  dbus send
    bus=system
    path=/org/freedesktop/UPower
    interface=org.freedesktop.UPower
    member=EnumerateDevices
    peer=(name=org.freedesktop.UPower),
``` 
I notice `ListMountableInfo` requirement on almost every desktop application (Gnome), following by `ListMonitorImplementations`. Additionally, there is `org.freedesktop.UPower`, but it's not very common. I see this only on Ubuntu and derivatives. This happens outside of file chooser dialog.
What do we do? Deny? Move into separate abstraction? Or include into `ubuntu-unity7-base.d` drop-in?

**Comment by roddhjav** [comment]
I have never had these requirment on Arch, so I think including it in a `ubuntu-unity7-base.d` drop in would be the best solution.
I don't have much experience with dbus in general, so I am open to advice.
