### ISSUE TITLE
unix receive type=stream protocol=0,  not currently supported

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#343]
After updating today, `aa-log` suggested adding 

`unix receive type=stream protocol=0,  # file_inherit` 

to various profiles. However, after adding that rule and reloading AppArmor I got the following error:

```
AppArmor-Analysefehler f?r /etc/apparmor.d in profile /etc/apparmor.d/local/findmnt in Zeile 1: unknown rule: 'protocol' conditional is not currently supported
Reload failed for Load AppArmor profiles.
```

**Comment by roddhjav** [comment]
By bad. I recently reworked this part and I forgot about this.
