### ISSUE TITLE
chrome_crashpad_handler and stacking

### ISSUE THREAD

**Issue by roddhjav** [roddhjav/apparmor.d#348]
### Discussed in https://github.com/roddhjav/apparmor.d/discussions/347

<div type='discussions-op-text'>

<sup>Originally posted by **curiosityseeker** May 31, 2024</sup>
Similarly as with Firefox, 

`@{lib_dirs}/chrome_crashpad_handler  rpx,`

in `abstractions/app/chromium` is causing an error. And as in `abstractions/app/firefox`  stacking solves the problem:

`@{lib_dirs}/chrome_crashpad_handler  rpx -> brave//&brave-crashpad-handler,`

However, that abstractions should also work for other Chromium-based browsers, so this rule should better be generalized. I'm not sure how to do this. What do you think?</div>

**Comment by roddhjav** [comment]
@curiosityseeker what does not work with: 
```
 @{lib_dirs}/chrome_crashpad_handler  rPx -> @{profile_name}//&@{profile_name}-crashpad-handler,
```

The alternative solution is to add `@{lib_dirs}/chrome_crashpad_handler  rPx -> brave//&brave-crashpad-handler` in the brave profile and to remove the rule in the abstraction.

**Comment by curiosityseeker** [comment]
> @curiosityseeker what does not work with?:
> 
> ```
>  @{lib_dirs}/chrome_crashpad_handler  rpx -> @{profile_name}//&@{profile_name}-crashpad-handler,

`aa-log` reports:
```
profile brave {
  /opt/brave-bin/chrome_crashpad_handler ix,  # profile transition not found
}
```
And starting `/usr/bin/brave` gives:

` [94073:94073:0603/182730.981969:FATAL:spawn_subprocess.cc(237)] posix_spawn /opt/brave-bin/chrome_crashpad_handler: Permission denied (13)`


> ```
> 
> The alternative solution is to add `@{lib_dirs}/chrome_crashpad_handler rPx -> brave//&brave-crashpad-handler` in the brave profile and to remove the rule in the abstraction.

Yes, I think that's the best solution. Btw., it just comes to my mind that there is a similar problem in `abstractions/app/firefox` once other Firefox-based browsers want to use that abstraction.
