### ISSUE TITLE
flatpak-app prevents steam from opening

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#368]
Denial log:

`apparmor="DENIED" operation="open" class="file" profile="flatpak-app" name="/run/parent/app/.ref" pid=2266268 comm="bwrap" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0`

![image](https://github.com/roddhjav/apparmor.d/assets/58333920/b68f4097-2812-4ae1-a22c-55f0c6110283)

Opening steam with flatpak-app in enforcing mode results in this error, clicking "Ok" closes steam.

**Comment by roddhjav** [comment]
Thanks, it should be fixed now.

Also, please follow the [documentation](https://apparmor.pujol.io/enforce/) to move to enforce mode, as it keeps in complain mode some profile (including `flatpak-app`).

**Comment by Stoppedpuma** [comment]
@roddhjav Unrelated to the original issue but is there a make flag or something to prevent updating from resetting to the default make mode (complain / enforce)? Having to re-enforce all the profiles I have enabled is a bit time consuming.

**Comment by Stoppedpuma** [comment]
I'm aware of that but I have additional profiles that aren't in enforcing from `make enforce` as well as some in complain mode from the flag as well. To rephrase what I meant, is there a way to have profile remain in their set enforced / complain modes after updates instead of just resetting them to defaults?
