### ISSUE TITLE
Enforced pavucontrol profile prevents pavucontrol from starting

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#371]
DENIED  pavucontrol open owner @{run}/user/@{uid}/dconf/user comm=pavucontrol requested_mask=wrc denied_mask=wrc
DENIED  pavucontrol open owner @{user_config_dirs}/dconf/user comm=pavucontrol requested_mask=r denied_mask=r
DENIED  pavucontrol open owner @{run}/user/@{uid}/dconf/user comm="dconf worker" requested_mask=wrc denied_mask=wrc
DENIED  pavucontrol open owner @{user_config_dirs}/dconf/user comm="dconf worker" requested_mask=r denied_mask=r
DENIED  pavucontrol open /usr/share/X11/xkb/rules/evdev comm=pavucontrol requested_mask=r denied_mask=r

**Comment by roddhjav** [comment]
Thanks, fixed.
