### ISSUE TITLE
xdg-document-portal breaks file uploads

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#375]
DENIED  xdg-permission-store open owner @{user_share_dirs}/flatpak/db/documents comm=pool-@{lib}/x requested_mask=wc denied_mask=wc
DENIED  xdg-document-portal open owner @{HOME}/image.png comm="fuse mainloop" requested_mask=r denied_mask=r

Included xdg-permission-store denial log in case that adds to anything

**Comment by roddhjav** [comment]
Thanks, it should be fixed now.

Note: you did not included any additional logs
