### ISSUE TITLE
xdg-mime prevents opening files from tui file managers

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#378]
DENIED  xdg-mime open @{PROC}/version comm=grep requested_mask=r denied_mask=r
DENIED  xdg-mime open /usr/share/file/misc/magic.mgc comm=file requested_mask=r denied_mask=r

Additional line from when the profile is in complain mode:

ALLOWED xdg-mime open owner @{HOME}/image.png comm=file requested_mask=r denied_mask=r

**Comment by roddhjav** [comment]
Thanks, this should be fixed for now. Later this profile will have to be fully redesigned.
