### ISSUE TITLE
aa-log error

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#382]
For `libreoffice` I get the following from `aa-logprof`:

`owner /home/*/.cache/event-sound-cache.tdb.eed35b34d31c43a195c88ebef6fe8908.x86_64-pc-linux-gnu k,`

while `aa-log` reports:

`owner @{user_cache_dirs}/event-sound-cache.tdb.@{hex32}.@{multiarch}  comm ,`

which doesn't look correct.

**Comment by roddhjav** [comment]
I need to improve the log cleanup process of aa-log. That should be fixed soon.

NB: it also means that the libreoffice profile needs the `audio-client` abstraction.
