### ISSUE TITLE
Include user fonts in fc-cache

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#387]
Current behaviour blocks common locations for user installed fonts such as ~/.fonts and ~/.local/share/fonts

**Comment by roddhjav** [comment]
Can you provide some logs (fonts is already in  fc-cache)

**Comment by roddhjav** [comment]
These are already present in the `fonts` abstraction. The only difference is the absence of `owner` in your log which seems problematic. How are you using `fc-cache`

**Comment by Stoppedpuma** [comment]
I completely forgot I had sudo in my alias for updating font cache, closing.
