### ISSUE TITLE
systemd-network prevents network from working on reboot

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#398]
Might be caused by VPN being loaded on start?

`DENIED  systemd-networkd open / comm=systemd-network requested_mask=r denied_mask=r`
`DENIED  systemd-networkd unlink owner @{run}/systemd/netif/io.systemd.Network comm=systemd-network requested_mask=d denied_mask=d`

**Comment by roddhjav** [comment]
My bad, the rules where simply too strict. This should now be fixed with f9a93ab.
