### ISSUE TITLE
Wireplumber breaks on reboot

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#399]
Enforcing the wireplumber profile causes only the dummy driver to be mapped on reboot. aa-log has no logs for some reason and journalctl only shows this:
`wireplumber[5151]: default: Failed to get percentage from UPower: org.freedesktop.DBus.Error.NameHasNoOwner`

I haven't tested with other pipewire related profiles so this could affect them as well.

**Comment by roddhjav** [comment]
This seems unrelated to apparmor: the profile already has access to `org.freedesktop.UPower` and this is not enforced on non Ubuntu distribution anyway.

**Comment by Stoppedpuma** [comment]
Setting the profile in complain mode fixes this, doesn't that make this an issue related to apparmor.d?

**Comment by Stoppedpuma** [comment]
This seems to just happen randomly with some profile in the `make enforce` profiles. No idea which ones as this seemed to happen randomly even when settings all pipewire related profiles and wireplumber  is set to complain, it just makes it possible to work correctly after a reboot. When I'm using my own list of enforced profiles I can't seem to reproduce this. Any ideas on where to go from here for debugging this? No logs are appearing anywhere besides the one I posted above.

**Comment by roddhjav** [comment]
Do you get any log from `aa-log -s` (even unrelated to wireplumber)?

**Comment by Stoppedpuma** [comment]
No

**Comment by Stoppedpuma** [comment]
It's also probably worth mentioning that I managed to get audio to work somehow by switching to TTY-2 and playing an audio file while using the `make enforce` profiles. I only managed to get this to work once but I also haven't tried it more than three or so times.

**Comment by roddhjav** [comment]
Hum, can you tell me more about you setup? Distribution, DE, how you enabled wireplumber?

**Comment by Stoppedpuma** [comment]
Arch Linux, Hyprland, Wireplumber starts through systemd service.

**Comment by roddhjav** [comment]
I have never tested Hyprland, so... I don't know (and I can't debug it)

**Comment by Stoppedpuma** [comment]
Still no logs unfortunately , I figured this out by setting every profile to enforce. Setting `systemd-logind` to complain fixes this.

**Comment by odomingao** [comment]
I'm also on Hyprland/Arch. I'd like to add that audio does work for me with systemd-logind on enforce, even though I also have the same error.

**Comment by roddhjav** [comment]
As it does not seems to be related to apparmor I am closing the issue.
