### ISSUE TITLE
xdg-dbus-proxy prevents opening files from download menus

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#400]
Similar to #386

Causes Firefox to crash instantly upon clicking on an item in the download menu.

`DENIED  xdg-dbus-proxy file_receive owner @{HOME}/downloads/image.png comm=xdg-dbus-proxy requested_mask=r denied_mask=r`

This error as well if the file isn't saved to downloads:

`DENIED  xdg-dbus-proxy file_receive owner @{run}/flatpak/doc/fd4a98d3/image.png comm=xdg-dbus-proxy requested_mask=r denied_mask=r`

**Comment by roddhjav** [comment]
Thanks, should be fixed now. These profiles may have to be revisited later.
