### ISSUE TITLE
Most Apparmor profiles are in complain mode by default.

### ISSUE THREAD

**Issue by IPlayZed** [roddhjav/apparmor.d#401]
Hi, according to the [relevant parts of the documentation](https://apparmor.pujol.io/usage/) there should be around _1050 profiles in enforce mode_.

However, when listing it via `sudo aa-status`, from the 1618 profiles, only 80 are set to be in enforce mode, 1538 are in complain mode and 122 processes are in complain mode.

Is this expected behaviour?

**Comment by IPlayZed** [comment]
I am also interested, if it is okay to manually set these complain profiles one-by-one into enforce mode?

**Comment by curiosityseeker** [comment]
https://apparmor.pujol.io/enforce/

**Comment by IPlayZed** [comment]
> https://apparmor.pujol.io/enforce/

I do understand how to put them into enforce mode, but if this is expected, then the documentation is a bit misleading.

**Comment by roddhjav** [comment]
This is documented in the warning message of https://apparmor.pujol.io/install. The output of `aa-status` in the usage section is only an example of possible output and should not be taken literally.

You can use `aa-enforce` to enforce a specific profile.

I am planning to improve the install section to add more detail about what can be done regarding profile in complain mode. To sum up (and in that order) you can:
1. Install apparmor.d in the (default) complain mode
2. Reboot
3. Check for any apparmor logs raised, [report any raised logs](https://apparmor.pujol.io/report/).
4. Use the profiles in complain mode for a while (a day, a week)
5. Regularly check for new apparmor logs.
6. Only if there is no logs raised for your daily usage, install in enforce mode.
