### ISSUE TITLE
All processes require `owner /dev/tty[0-9]* rw,` when invoked from local console (Ctrl+Alt+F#)

### ISSUE THREAD

**Issue by nobodysu** [roddhjav/apparmor.d#41]
Possible solutions:
1. Do nothing. This cripples troubleshooting in case of DE issues.
2. Add a line to `consoles` abstraction, since all such processes also require it. (`consoles` does not have `local` include)
3. Add this line to every console-related profile.

**Comment by roddhjav** [comment]
According to the issue raised in https://gitlab.com/apparmor/apparmor/-/issues/92 I think for now the first solution (do nothing) could be the best.

**Comment by nobodysu** [comment]
:(

**Comment by nobodysu** [comment]
```
$ grep -rI '/dev/tty\[0-9\]\*' apparmor.d | wc -l
164
```
Should we revisit these older entries then?

**Comment by roddhjav** [comment]
Certainly not, `if it ain't broke don't fix it`. But more seriously, beware before wanting to automatically update over 100 profiles. This is the best way to break your system down.

**Comment by nobodysu** [comment]
Well, if it's against the current policy I consider it broken.
I rather talked about rechecking whether individual profile (which is being worked on) needs this `tty` entry, if not started from terminal.

**Comment by roddhjav** [comment]
Ok this seems better, it might be time consuming though.

**Comment by nobodysu** [comment]
Yeah, that would be a long process. On it.

**Comment by beroal** [comment]
Do I understand this correctly that the profile of every program that interacts via a console should contain the following?
```
/dev/tty rw,
```
I believe that `/dev/tty` is enough.
