### ISSUE TITLE
Gnome's file manager does not open specific locations anymore like /opt

### ISSUE THREAD

**Issue by shahineft** [roddhjav/apparmor.d#413]
Of course you can sudo ls -la /opt to see whats inside. It's obvious that this is an access restriction.

**Comment by roddhjav** [comment]
It is a feature, nautilus (and the other files manager) are only allowed to display user files.

You can bypass this policy yourself by creating `/etc/apparmor.d/local/nautilus` with the content:
```
  /** r,
```

**Comment by shahineft** [comment]
Thank you. Is it also please possible to update the aur repository of the project? 

This is the last update:

Last Updated: 	2023-11-23 16:20 (UTC)

By the way, this project is a great work! I say this as a student.

**Comment by roddhjav** [comment]
It is a `-git` repository, it does not need to be updated. When you install it with an aur helper (like yay), the helper will check for new commit and build a new package if needed.
