### ISSUE TITLE
Every process on Armbian require `@{exec_path} mr,` in order to run

### ISSUE THREAD

**Issue by nobodysu** [roddhjav/apparmor.d#42]
This is not an issue on DietPi however. Maybe it's related to some debugging compilation?
I don't know how `m` affects the security. What will be the course of action?

**Comment by roddhjav** [comment]
That's is normal, every profile needs an `mr` rule for its main exec path.

The memory map is usually used to execute a binary initially read in memory. So this is how lib are loaded. As example you can see in the base abstraction (`/etc/apparmor.d/abstractions/base`) that all `.so` lib in `/usr/lib/` have an `mr` rule.

However, it can cause security issues when a program (an attacker) is allowed to write a file that will be memory mapped later.
This is why there is usually no `w` rule with a `m` rule. Ensuring this (among other thing) ensure us to enforce a strict [write xor execute] (W^X) mode on most of the profile.

[write xor execute]: https://en.wikipedia.org/wiki/W%5EX

**Comment by nobodysu** [comment]
Thanks for the info.
Should I add `m` directive to *all* profiles, or just commonly used on Armbian?

**Comment by roddhjav** [comment]
It is already present for most of the profile. And should be included for all new project (see the contribution file). Only some profile do not need it (about 100 at the moment).

**Comment by nobodysu** [comment]
Correction: it's every *binary*. Scripts, including python, does not need the `mmap`.
