### ISSUE TITLE
Issue - GSConnect & Others - Logs provided

### ISSUE THREAD

**Issue by DimSystem** [roddhjav/apparmor.d#422]
Hi! So my apparmor is really noisy for this extension on gnome, and other allowed software

type=AVC msg=audit(1721440545.818:26011): apparmor="ALLOWED" operation="getattr" class="file" profile="dbus-session//null-/home/newsexodus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js//null-/usr/bin/gjs-console//null-/home/newsexodus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences//null-/usr/bin/gjs-console" name="/proc/16850/stat" pid=16850 comm="gjs" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000

how to fix it? tried genprof, aa-logprof and no results.. Please feel free to ask for more logs.. Im on opensuse tumbleweed

[logs.zip](https://github.com/user-attachments/files/16318541/logs.zip)

thank you!!

**Comment by roddhjav** [comment]
Thanks, it should be fixed now.

For keepass, you need to set `@{XDG_PASSWORD_STORE_DIR}` (see https://apparmor.pujol.io/configuration/#personal-directories) to your kdbx file directory.

Nautilus,  gnome-text-editor, and any other file browser/web browser/user text editor do not have access to system files such as `/etc/apparmor.d`. It is a feature. See #413

**Comment by roddhjav** [comment]
It is a bug in apparmor tooling, it is being fixed on they side. For now, you can remove the non .apparmor.d version.

**Comment by roddhjav** [comment]
This profile allow full read write to your home directory. So, yes it works... Not having a profile at all would work too.
