### ISSUE TITLE
transmission-gtk and transmission-qt conflict with upstream transmission profile

### ISSUE THREAD

**Issue by cboltz** [roddhjav/apparmor.d#429]
Upstream AppArmor (since 4.0) includes a "transmission" profile, which includes profiles for transmission-{daemon,cli,gtk,qt}.

apparmor.d includes profiles for transmission-gtk and transmission-qt profiles - different filenames, but same profile name, and therefore they conflict with the upstream profiles.

The best way to fix this conflict would be to merge these two profiles into the upstream profiles ;-)

**Comment by roddhjav** [comment]
Thanks, it should be fixed now.

Merging my profile with upstream would be the best fix. However, as I use my own set of extension, they would need to be merged first, as well as the [tunables](https://gitlab.com/apparmor/apparmor/-/merge_requests/1088).
