### ISSUE TITLE
Failing to mount Borg Backup

### ISSUE THREAD

**Issue by Gajus84** [roddhjav/apparmor.d#431]
Maybe I can get some advise here:

Tying to mount a borg backup in /mnt/  results in

```
fusermount: failed to open mountpoint for reading: Permission denied
Runtime Error: FUSE mount failed
```

with aa-log output:

```
DENIED  borg//fusermount open /mnt/Borg/ comm=fusermount requested_mask=r denied_mask=r
DENIED  borg mount owner /mnt/Borg/ info="failed mntpnt match" comm=borg srcname=borgfs flags="ro, nosuid, nodev" error=-13 fstype=fuse
```

Not sure what to do tbh. I've tried to solve it with a local borg and fusermount containing

`mount fstype=fuse options=(ro nodev nosuid) borgfs -> /mnt/Borg/,`

and (in fusermount and borg)

`/mnt/Borg/ rw,`

but no luck.

Any advise would be welcomed. Thank you.

**Comment by roddhjav** [comment]
Thanks for these logs. I recently reworked this profile, however, I restricted it too much. It should be fixed now.
