### ISSUE TITLE
Can't open QEMU virtual machines

### ISSUE THREAD

**Issue by EricLin0509** [roddhjav/apparmor.d#436]
Here is the log of the QEMU

`char device redirected to /dev/pts/0 (label charserial0)
2024-08-08T03:31:42.954776Z qemu-system-x86_64: terminating on signal 15 from pid 8568 (/usr/bin/virtqemud)
2024-08-08 03:31:43.756+0000: shutting down, reason=shutdown`

and I check the aa-log and I found profile unix-chkpwd cause this problem. Here is the log of the aa-log:
`apparmor="DENIED" operation="file_lock" class="file" profile="unix-chkpwd" name="/dev/pts/0"  comm="sudo" requested_mask="k" denied_mask="k" fsuid=0 ouid=1000 FSUID="root" OUID="EricLin"
`

**Comment by EricLin0509** [comment]
After adding these lines, QEMU virtual machines can work with profile unix-chkpwd in enforce mode

**Comment by EricLin0509** [comment]
virtlogd can work after adding
> owner @{run}/user/@{uid}/libvirt/common/system.token rwk,
to /etc/apparmor.d/local/virtlogd

**Comment by roddhjav** [comment]
Thanks, should be fixed now.
