### ISSUE TITLE
flatpak exports missing from freedesktop.org/complete abstraction

### ISSUE THREAD

**Issue by odomingao** [roddhjav/apparmor.d#437]
Hi, could this be added to the freedesktop.org complete abstraction?

```
  /var/lib/flatpak/exports/share/applications/{,**} r,
  /var/lib/flatpak/exports/share/icons/{,**} r,
  /var/lib/flatpak/exports/share/mime/{,**} r,
```

Thanks.

**Comment by roddhjav** [comment]
That should already be handled in the freedesktop abstraction under the `@{system_share_dirs}` variable. Do you have any logs that would indicate a missing path?

**Comment by odomingao** [comment]
You're right. I had noticed the complaint when making a new profile, and grepping for flatpak/exports in the abstractions dir wielded no results so I assumed it was missing since the snap one was explicitly included in the abstraction, my bad. Removing these lines from the profile results in no complaints, so I'll close the issue.
