### ISSUE TITLE
sshd daemon didn't work

### ISSUE THREAD

**Issue by EricLin0509** [roddhjav/apparmor.d#442]
When I connect my device via ssh, it show me a error message: kex_exchange_identification: read: Connection reset by peer

Here is the log (in complain mode): 
`apparmor="DENIED" operation="exec" class="file" profile="sshd" name="/usr/lib/ssh/sshd-session"  comm="sshd" requested_mask="x" denied_mask="x" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="exec" class="file" profile="sshd" name="/usr/lib/ssh/sshd-session"  comm="sshd" requested_mask="x" denied_mask="x" fsuid=0 ouid=0 target="sshd//null-/usr/lib/ssh/sshd-session" FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/ssh/sshd-session"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/proc/sys/kernel/cap_last_cap"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/ssl/openssl.cnf"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/ssl/openssl.cnf"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/gai.conf"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/gai.conf"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/nsswitch.conf"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/nsswitch.conf"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/passwd"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/passwd"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="capable" class="cap" profile="sshd//null-/usr/lib/ssh/sshd-session"  comm="sshd-session" capability=18  capname="sys_chroot"
apparmor="ALLOWED" operation="capable" class="cap" profile="sshd//null-/usr/lib/ssh/sshd-session"  comm="sshd-session" capability=6  capname="setgid"
apparmor="ALLOWED" operation="capable" class="cap" profile="sshd//null-/usr/lib/ssh/sshd-session"  comm="sshd-session" capability=7  capname="setuid"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/bin/bash"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/pam.d/"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/pam.d/sshd"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/pam.d/sshd"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/pam.d/system-remote-login"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/pam.d/system-remote-login"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/pam.d/system-login"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/pam.d/system-login"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_shells.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_shells.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_shells.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_nologin.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_nologin.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_nologin.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/pam.d/system-auth"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/pam.d/system-auth"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_faillock.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_faillock.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_faillock.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_systemd_home.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_systemd_home.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_systemd_home.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_unix.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_unix.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_unix.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_permit.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_permit.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_permit.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_env.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_env.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_env.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_access.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_access.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_access.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_time.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_time.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_time.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_loginuid.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_loginuid.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_loginuid.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_keyinit.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_keyinit.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_keyinit.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_limits.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_limits.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_limits.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_motd.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_motd.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_motd.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_mail.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_mail.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_mail.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_umask.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_umask.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_umask.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_systemd.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_systemd.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_systemd.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/pam.d/other"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/etc/pam.d/other"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_deny.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_deny.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_deny.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_warn.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="getattr" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_warn.so"  comm="sshd-session" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="sshd//null-/usr/lib/ssh/sshd-session" name="/usr/lib/security/pam_warn.so"  comm="sshd-session" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="capable" class="cap" profile="sshd//null-/usr/lib/ssh/sshd-session"  comm="sshd-session" capability=29  capname="audit_write"`

**Comment by roddhjav** [comment]
Thanks for the catch. Fixed.
