### ISSUE TITLE
Pikaur and Timeshift doens't work

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [roddhjav/apparmor.d#444]
I'm understand that is necessary a big bunch in profiles, but i'm newbie, if i'm trying to enable it what is the best way? put all in complain and use a apparmor generator doesn't looks to be the better when i'm trying to enable timeshift, exist other way to generate apparmor profile for a newbie?

Distro: Arch Linux 
DE: Gnome
Apparmor: Enforce mode

**Comment by roddhjav** [comment]
Please provide logs in complain mode as shown in: https://apparmor.pujol.io/report/

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> The first recommendation is after install to regularly check AppArmor log with [aa-log](https://apparmor.pujol.io/usage/#apparmor-log). You can also configure [a desktop notification on denied actions](https://wiki.archlinux.org/title/AppArmor#Get_desktop_notification_on_DENIED_actions).
> 
> Please provide logs in complain mode as shown in: https://apparmor.pujol.io/report/

Thank you, i will try

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> Please provide logs in complain mode as shown in: https://apparmor.pujol.io/report/

`[1;31mDENIED [0m [34mgnome-characters[0m [33mopen[0m[35m owner[0m [35m@{user_cache_dirs}/mesa_shader_cache_db/part0/mesa_cache.db[0m comm=gnome-character requested_mask=[1;31mrc[0m denied_mask=[1;31mrc[0m
[1;31mDENIED [0m [34mgnome-characters[0m [33mopen[0m[35m owner[0m [35m@{user_cache_dirs}/mesa_shader_cache_db/part0/mesa_cache.db[0m comm=gnome-character requested_mask=[1;31mwr[0m denied_mask=[1;31mwr[0m
[1;31mDENIED [0m [34morg.gnome.NautilusPreviewer[0m [33mopen[0m[35m owner[0m [35m@{user_cache_dirs}/mesa_shader_cache_db/part0/mesa_cache.db[0m comm=org.gnome.Nauti requested_mask=[1;31mc[0m denied_mask=[1;31mc[0m
[1;31mDENIED [0m [34morg.gnome.NautilusPreviewer[0m [33mopen[0m[35m owner[0m [35m@{user_cache_dirs}/mesa_shader_cache_db/part0/mesa_cache.db[0m comm=org.gnome.Nauti requested_mask=[1;31mw[0m denied_mask=[1;31mw[0m
[1;31mDENIED [0m [34mnautilus[0m [33mfile_lock[0m[35m owner[0m [35m@{user_cache_dirs}/mesa_shader_cache_db/part0/mesa_cache.db[0m comm=nautilus requested_mask=[1;31mk[0m denied_mask=[1;31mk[0m
[1;31mDENIED [0m [34mxwayland[0m [33mopen[0m[35m owner[0m [35m@{user_cache_dirs}/mesa_shader_cache_db/part0/mesa_cache.db[0m comm=Xwayland requested_mask=[1;31mrc[0m denied_mask=[1;31mrc[0m
[1;31mDENIED [0m [34mxwayland[0m [33mopen[0m[35m owner[0m [35m@{user_cache_dirs}/mesa_shader_cache_db/part0/mesa_cache.db[0m comm=Xwayland requested_mask=[1;31mwr[0m denied_mask=[1;31mwr[0m
[1;31mDENIED [0m [34mgsd-xsettings[0m [33mopen[0m[35m owner[0m [35m@{user_cache_dirs}/mesa_shader_cache_db/part0/mesa_cache.db[0m comm=gsd-xsettings requested_mask=[1;31mrc[0m denied_mask=[1;31mrc[0m
[1;31mDENIED [0m [34mgsd-xsettings[0m [33mopen[0m[35m owner[0m [35m@{user_cache_dirs}/mesa_shader_cache_db/part0/mesa_cache.db[0m comm=gsd-xsettings requested_mask=[1;31mwr[0m denied_mask=[1;31mwr[0m
[1;31mDENIED [0m [34mmutter-x11-frames[0m [33mopen[0m[35m owner[0m [35m@{user_cache_dirs}/mesa_shader_cache_db/part0/mesa_cache.db[0m comm=mutter-x11-fram requested_mask=[1;31mrc[0m denied_mask=[1;31mrc[0m
[1;31mDENIED [0m [34mmutter-x11-frames[0m [33mopen[0m[35m owner[0m [35m@{user_cache_dirs}/mesa_shader_cache_db/part0/mesa_cache.db[0m comm=mutter-x11-fram requested_mask=[1;31mwr[0m denied_mask=[1;31mwr[0m
[1;31mDENIED [0m [34mbtrfs[0m [33mopen[0m[35m owner[0m [35m@{run}/timeshift/5974/backup/[0m comm=btrfs requested_mask=[1;31mr[0m denied_mask=[1;31mr[0m
[1;31mDENIED [0m [34mdf[0m [33mopen[0m[35m owner[0m [35m/dev/dm-0[0m comm=df requested_mask=[1;31mr[0m denied_mask=[1;31mr[0m
[1;31mDENIED [0m [34mbtrfs[0m [33mopen[0m[35m owner[0m [35m@{run}/timeshift/5974/backup/timeshift-btrfs/snapshots/2024-08-23_17-38-41/[0m comm=btrfs requested_mask=[1;31mr[0m denied_mask=[1;31mr[0m
[1;31mDENIED [0m [34mgit[0m [33mopen[0m[35m owner[0m [35m@{user_share_dirs}/pikaur/aur_repos/gtk4-git/[0m comm=git requested_mask=[1;31mr[0m denied_mask=[1;31mr[0m
[1;31mDENIED [0m [34mxdg-document-portal[0m [33mopen[0m[35m owner[0m [35m@{HOME}/log.txt[0m comm="fuse mainloop" requested_mask=[1;31mr[0m denied_mask=[1;31mr[0m
`

**Comment by EliasTheGrandMasterOfMistakes** [comment]
[log.txt](https://github.com/user-attachments/files/16733555/log.txt)
Sorry for delay
[logdenied.txt](https://github.com/user-attachments/files/16733557/logdenied.txt)

[logtext.txt](https://github.com/user-attachments/files/16733558/logtext.txt)

**Comment by EliasTheGrandMasterOfMistakes** [comment]
Timeshift:

btrfs:
 ```
apparmor="DENIED" operation="open" class="file" profile="btrfs" name="/run/timeshift/5974/backup/"  comm="btrfs" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="DENIED" operation="open" class="file" profile="btrfs" name="/run/timeshift/5974/backup/timeshift-btrfs/snapshots/2024-08-23_17-38-41/"  comm="btrfs" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="DENIED" operation="open" class="file" profile="btrfs" name="/run/timeshift/4842/backup/"  comm="btrfs" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="DENIED" operation="open" class="file" profile="btrfs" name="/run/timeshift/4842/backup/timeshift-btrfs/snapshots/2024-08-24_00-22-48/"  comm="btrfs" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
```


df:
``` 
apparmor="DENIED" operation="open" class="file" profile="df" name="/dev/dm-0"  comm="df" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
```bash


Gnome shell:

**Comment by EliasTheGrandMasterOfMistakes** [comment]
xdg-document-portal 

```
apparmor="DENIED" operation="open" class="file" profile="xdg-document-portal" name="/home/user/log.txt"  comm="fuse mainloop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="ratatouille" OUID="ratatouille"
apparmor="DENIED" operation="open" class="file" profile="xdg-document-portal" name="/home/user/gnome.txt"  comm="fuse mainloop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="ratatouille" OUID="ratatouille"
```

**Comment by EliasTheGrandMasterOfMistakes** [comment]
Have much more of logs? i need to getting all including the big gnome-shell and nm-openvpn? if been necessary i can put all in a big file with sections per app or is better multiple files?

**Comment by EliasTheGrandMasterOfMistakes** [comment]
Sorry for my mistakes, i have generate new logs for better visualization
[log-1.txt](https://github.com/user-attachments/files/16742229/log-1.txt)
[logbtrfs.txt](https://github.com/user-attachments/files/16742230/logbtrfs.txt)
[logdf.txt](https://github.com/user-attachments/files/16742231/logdf.txt)
[logepiphany-search.txt](https://github.com/user-attachments/files/16742232/logepiphany-search.txt)
[logflatpak.txt](https://github.com/user-attachments/files/16742233/logflatpak.txt)
[logflatpak-1.txt](https://github.com/user-attachments/files/16742234/logflatpak-1.txt)
[loggit.txt](https://github.com/user-attachments/files/16742235/loggit.txt)
[lognautilus.txt](https://github.com/user-attachments/files/16742236/lognautilus.txt)
[logshell.txt](https://github.com/user-attachments/files/16742237/logshell.txt)
[logshell-1.txt](https://github.com/user-attachments/files/16742238/logshell-1.txt)
[logxdg.txt](https://github.com/user-attachments/files/16742239/logxdg.txt)
[logxdgdocument.txt](https://github.com/user-attachments/files/16742240/logxdgdocument.txt)
[orgnautilus.txt](https://github.com/user-attachments/files/16742241/orgnautilus.txt)

**Comment by roddhjav** [comment]
All of these should be fixed now. Most of them where related to #450

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> All of these should be fixed now. Most of them where related to #450

thank you
