### ISSUE TITLE
Can't generate a new GPG key

### ISSUE THREAD

**Issue by EricLin0509** [roddhjav/apparmor.d#448]
Here is the log:
`apparmor="DENIED" operation="open" class="file" profile="gpg" name="/usr/share/terminfo/x/xterm-256color"  comm="gpg" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="EricLin" OUID="root"
apparmor="DENIED" operation="open" class="file" profile="gpg-agent" name="/home/EricLin/.gnupg/common.conf"  comm="gpg-agent" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="EricLin" OUID="EricLin"
apparmor="DENIED" operation="exec" class="file" profile="pinentry" name="/usr/bin/ldd"  comm="pinentry" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0 FSUID="EricLin" OUID="root"
apparmor="DENIED" operation="open" class="file" profile="pinentry" name="/usr/bin/ldd"  comm="pinentry" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="EricLin" OUID="root"
apparmor="DENIED" operation="mknod" class="file" profile="gpg-agent" name="/home/EricLin/.gnupg/private-keys-v1.d/29F325B2FC1D170FA97C80E753B4859537AC81B9.key.tmp"  comm="gpg-agent" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000 FSUID="EricLin" OUID="EricLin"`

**Comment by EricLin0509** [comment]
It still not working. I found more logs:
`apparmor="DENIED" operation="open" class="file" profile="scdaemon" name="/home/EricLin/.gnupg/common.conf"  comm="scdaemon" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="EricLin" OUID="EricLin"
apparmor="DENIED" operation="exec" class="file" profile="pinentry" name="/usr/bin/ldd"  comm="pinentry" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0 FSUID="EricLin" OUID="root"
apparmor="DENIED" operation="open" class="file" profile="pinentry" name="/usr/bin/ldd"  comm="pinentry" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="EricLin" OUID="root"
`

**Comment by roddhjav** [comment]
I am not fixing issue in enforce mode anymore, it is a waste of time. Please don't waste mine.
