### ISSUE TITLE
zramctl doesn't show algorithm, data, compression, total, streams, mountpoint

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#456]
ALLOWED zramctl open @{sys}/devices/virtual/block/zram0/comp_algorithm comm=zramctl requested_mask=r denied_mask=r
ALLOWED zramctl open @{sys}/devices/virtual/block/zram0/mm_stat comm=zramctl requested_mask=r denied_mask=r
ALLOWED zramctl open @{sys}/devices/virtual/block/zram0/max_comp_streams comm=zramctl requested_mask=r denied_mask=r
ALLOWED zramctl open @{PROC}/swaps comm=zramctl requested_mask=r denied_mask=r

**Comment by curiosityseeker** [comment]
I had already added 

```
@{sys}/devices/virtual/block/zram@{int}/comp_algorithm r,
@{sys}/devices/virtual/block/zram@{int}/max_comp_streams r,
@{sys}/devices/virtual/block/zram@{int}/mm_stat r,

      @{PROC}/swaps r,
owner @{PROC}/@{pid}/mounts r,
```
to `local/zramctl` and intended a corresponding commit.
