### ISSUE TITLE
EndeavourOS (Arch) log report

### ISSUE THREAD

**Issue by PhysicsIsAwesome** [roddhjav/apparmor.d#470]
`aa-log -R` output in complain mode: https://pastebin.com/bwCJgmTh

Operating System: EndeavourOS
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.8-hardened1-1-hardened (64-bit)
Graphics Platform: Wayland

**Comment by roddhjav** [comment]
Thanks, it should be fixed now.

**Comment by PhysicsIsAwesome** [comment]
Thank you!
