### ISSUE TITLE
.thunderbird/.firefox folders are inaccessible

### ISSUE THREAD

**Issue by Cherkah** [roddhjav/apparmor.d#476]
i cannot access to my $HOME/.thunderbird -.firefox folders (via dolphin) since apparmor is installed.
no problem via a terminal.

all logs that i got are:
```
apparmor="ALLOWED" operation="open" class="file" profile="xwayland" name="/"  comm="Xwayland" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="cherkab" OUID="root"

apparmor="ALLOWED" operation="open" class="file" profile="firefox" name="/"  comm="Renderer" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="cherkab" OUID="root"
```
i've tried to set the flags `userns` for each of concerned profile in ../apparmor.d/local/ but nothings cause:
1) profile in complain mode
2) userns flag is defined in apparmor V4.1 not V3.1

if apparmor.d is disabled i can access to these folders in my user workspace.

So what can i do?

**Comment by roddhjav** [comment]
It is a feature, file browsers have access to all user directories, however, they are prevented to display sensitive directories such as `~/.ssh`, `~/.gpg`, `~/.mozilla`, `.thunderbird`.

See the entire list here: https://github.com/roddhjav/apparmor.d/blob/main/apparmor.d/abstractions/deny-sensitive-home

**Comment by Cherkah** [comment]
ok thanks. i've turned around the repo but never found this deny-sensitive-home file!
can be closed.

PS: what do you recommend withe journalctl.conf: "volatile", "persistent", "auto" (apparmor+audit)
so as to not flooding too much the log folder arch recommand volatil as persistent for others reasons
