### ISSUE TITLE
Creating a profile for gamescope

### ISSUE THREAD

**Issue by odomingao** [roddhjav/apparmor.d#478]
gamescope, if launched in a sandbox, will result in denies in the xwayland profile similarly to my previous issue with Steam. Creating a profile for it, even if it's always in complain mode, will fix the issue. 

The profile below works fine for glxgears, but will break with other applications because gamescope will want the permissions that whatever program launched through it wants, and I don't know how to address this other than granting extremely wide permissions.

```
abi <abi/3.0>,

include <tunables/global>

@{exec_path} = @{bin}/gamescope
profile gamescope /usr/bin/gamescope flags=(attach_disconnected,complain) {
  include <abstractions/base>
  include <abstractions/app-launcher-user>
  include <abstractions/audio-client>
  include <abstractions/desktop>
  include <abstractions/graphics>
  include <abstractions/nameservice-strict>

  @{exec_path} mr,

  owner @{run}/user/@{uid}/gamescope-@{int} w,
  owner @{run}/user/@{uid}/gamescope-@{int}.lock rwk,
  owner @{run}/user/@{uid}/gamescope-@{int}-ei w,
  owner @{run}/user/@{uid}/gamescope-@{int}-ei.lock rwk,
  owner @{run}/user/@{uid}/gamescope-limiter-@{rand8} rw,
  owner @{run}/user/@{uid}/gamescope-shm-@{rand8} rw,
  owner @{run}/user/@{uid}/server-@{int}.xkm rw,

        @{PROC}/ r,
        @{PROC}/@{pid}/stat r,
  owner @{PROC}/@{pid}/cmdline r,
  owner @{PROC}/@{pid}/fd/ r,
  owner @{PROC}/@{pid}/mounts r,

  include if exists <local/gamescope>
}

# vim:syntax=apparmor
```

**Comment by roddhjav** [comment]
The only solution is to give a lot of access. For reference you can check what I did for steam:
- You split the runner/launcher (here gamescope) and the game you want to run
- The game profile, in this context it would be something like `gamescope-game` uses the `common/game` that give some wide permissions. But does not allow access to user data.

See:
https://github.com/roddhjav/apparmor.d/blob/fb93ac0df35346019181d96bee9624925e04fb84/apparmor.d/profiles-s-z/steam#L5-L18

Alternative solution is flatpack:
- There is the sandbox manager (`flatpak`) and the profile for the apps (`flatpack-app`)
- flatpack-app need to give access to user data and other resources. It is way larger than a game only profile.

See:
https://github.com/roddhjav/apparmor.d/blob/fb93ac0df35346019181d96bee9624925e04fb84/apparmor.d/profiles-a-f/flatpak-app#L5-L19

**Comment by odomingao** [comment]
Thank you!
