### ISSUE TITLE
journalctl prints nothing

### ISSUE THREAD

**Issue by beroal** [roddhjav/apparmor.d#480]
When I run `journalctl` in a virtual terminal, the log shows that it requests access to `/dev/tty2`, but it only has access to `/dev/tty`, as far as I see.

**Comment by roddhjav** [comment]
I don't understand the issue, is journalctl working as expected?

**Comment by beroal** [comment]
I do this in a console.

If the `journalctl` and `child-pager` profiles are in the complain mode, I get the following log:
```
apparmor="ALLOWED" operation="file_inherit" class="file" profile="child-pager" name="/dev/tty2"  comm="less" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="child-pager" name="/dev/tty2"  comm="less" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
```
and `journalctl` prints a large log.

If they are in the enforce mode, `journalctl` doesn't print what it prints when they are in the complain mode.
