### ISSUE TITLE
slow boot and reload

### ISSUE THREAD

**Issue by beroal** [roddhjav/apparmor.d#481]
I recently switched from my profiles to your profiles and noticed that reloading profiles takes 40 s. Is it just me? If it's not just me, are there ways to optimize profile reload?

**Comment by roddhjav** [comment]
Yes, it is normal. There are some way to speed it up: https://apparmor.pujol.io/configuration/#apparmor

**Comment by beroal** [comment]
> Yes, it is normal. There are some way to speed it up: https://apparmor.pujol.io/configuration/#apparmor

Thanks. It's much faster now. I missed this feature somehow.
