### ISSUE TITLE
EndeavourOS new logs

### ISSUE THREAD

**Issue by PhysicsIsAwesome** [roddhjav/apparmor.d#484]
Operating System: EndeavourOS 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.8-hardened1-2-hardened (64-bit)
Graphics Platform: Wayland
apparmor.d-git 0.2729-1

Logs in three pastes due to size limitation:

https://pastebin.com/UydsbPNV
https://pastebin.com/L46Exfqq
https://pastebin.com/QxarnqYY

**Comment by roddhjav** [comment]
Thanks, they should be fixed now.
