### ISSUE TITLE
ufw can't determine iptables version

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#485]
`sudo ufw status`
ERROR: Couldn't determine iptables version

Logs in enforcing:

DENIED  ufw exec owner @{bin}/xtables-legacy-multi comm=python3 requested_mask=x denied_mask=x

Logs in complain:

ALLOWED ufw//null-@{bin}/xtables-legacy-multi getattr owner @{lib}/xtables/libxt_multiport.so comm=iptables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi open owner @{lib}/xtables/libxt_multiport.so comm=iptables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi file_mmap owner @{lib}/xtables/libxt_multiport.so comm=iptables requested_mask=rm denied_mask=rm
ALLOWED ufw//null-@{bin}/xtables-legacy-multi getattr owner @{PROC}/@{pid}/net/ip_tables_names comm=iptables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi getattr owner @{lib}/xtables/libxt_tcp.so comm=iptables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi open owner @{lib}/xtables/libxt_tcp.so comm=iptables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi file_mmap owner @{lib}/xtables/libxt_tcp.so comm=iptables requested_mask=rm denied_mask=rm
ALLOWED ufw//null-@{bin}/xtables-legacy-multi getattr owner @{lib}/xtables/libxt_udp.so comm=iptables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi open owner @{lib}/xtables/libxt_udp.so comm=iptables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi file_mmap owner @{lib}/xtables/libxt_udp.so comm=iptables requested_mask=rm denied_mask=rm
ALLOWED ufw//null-@{bin}/xtables-legacy-multi getattr owner @{lib}/xtables/libxt_multiport.so comm=ip6tables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi open owner @{lib}/xtables/libxt_multiport.so comm=ip6tables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi file_mmap owner @{lib}/xtables/libxt_multiport.so comm=ip6tables requested_mask=rm denied_mask=rm
ALLOWED ufw//null-@{bin}/xtables-legacy-multi getattr owner @{PROC}/@{pid}/net/ip6_tables_names comm=ip6tables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi getattr owner @{lib}/xtables/libxt_tcp.so comm=ip6tables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi open owner @{lib}/xtables/libxt_tcp.so comm=ip6tables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi file_mmap owner @{lib}/xtables/libxt_tcp.so comm=ip6tables requested_mask=rm denied_mask=rm
ALLOWED ufw//null-@{bin}/xtables-legacy-multi getattr owner @{lib}/xtables/libxt_udp.so comm=ip6tables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi open owner @{lib}/xtables/libxt_udp.so comm=ip6tables requested_mask=r denied_mask=r
ALLOWED ufw//null-@{bin}/xtables-legacy-multi file_mmap owner @{lib}/xtables/libxt_udp.so comm=ip6tables requested_mask=rm denied_mask=rm

**Comment by roddhjav** [comment]
Fixed thanks.
