### ISSUE TITLE
Tor Browser profile should not give access to anything sensitive or identifying

### ISSUE THREAD

**Issue by PhysicsIsAwesome** [roddhjav/apparmor.d#490]
Considering Tor Browser's use cases, profile `torbrowser` should not give access to anything sensitive or identifying and be as strict as possible, to keep damage small in case of a sandbox escape.

For example it has the line `include <abstractions/app/firefox>`, which includes the following to give Tor Browser access to some sensitive user files: 
```
include <abstractions/user-download-strict>
include <abstractions/user-read-strict>
```

"Tor Browser Launcher" uses the following profile, as a an example, with no access to these files. User files interaction like downloads happen through a Tor Browser-specific folder. https://github.com/torproject/torbrowser-launcher/blob/main/apparmor/torbrowser.Browser.firefox

It might make sense to also limit browsers in general to only have access to browser specific folders, e.g. each browser has it's own upload/download folder.

**Comment by roddhjav** [comment]
You have a good point, I will fix this shortly.

> It might make sense to also limit browsers in general to only have access to browser specific folders, e.g. each browser has it's own upload/download folder.

That is a no go as it would break a legitimate usage of a classic web browser. Unless you are volunteer to answer any issues from user that would be complaining that they can't upload any document they have...

**Comment by beroal** [comment]
> It might make sense to also limit browsers in general to only have access to browser specific folders, e.g. each browser has it's own upload/download folder.

This feature might make sense for every program that works with documents. I can't help but to advertise my relevant question #339.

> That is a no go as it would break a legitimate usage of a classic web browser. Unless you are volunteer to answer any issues from user that would be complaining that they can't upload any document they have...

The above feature may be turned off by default and turning it on may show a corresponding disclaimer.
