### ISSUE TITLE
Confused about the signal-desktop profile

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#505]
After every update there is the following code block in the `signal-desktop` profile between the `/dev/tty rw,` and the `include if exists <local/signal-desktop>` lines:

```
# Stacked profile: xdg-settings
  include <abstractions/consoles>
  include <abstractions/freedesktop.org>
  @{sh_path}        rix,
  @{bin}/{,e}grep   rix,
  @{bin}/basename   rix,
  @{bin}/cat        rix,
  @{bin}/cut        rix,
  @{bin}/mktemp     rix,
  @{bin}/mv         rix,
  @{bin}/readlink   rix,
  @{bin}/realpath   rix,
  @{bin}/sed        rix,
  @{bin}/sort       rix,
  @{bin}/uname      rix,
  @{bin}/wc         rix,
  @{bin}/which{,.debianutils}      rix,
  @{bin}/dbus-launch  rCx -> dbus,
  @{bin}/dbus-send    rCx -> dbus,
  @{bin}/kreadconfig5 rPx,
  @{bin}/xdg-mime     rPx,
  @{bin}/xprop        rPx,
  /usr/share/terminfo/** r,
  /etc/xdg/xfce4/helpers.rc r,
  /etc/machine-id r,
  /var/lib/dbus/machine-id r,
  owner @{HOME}/ r,
  owner @{HOME}/.Xauthority r,
  owner @{user_config_dirs}/xfce4/helpers.rc{,.*} rw,
  owner @{run}/user/@{uid}/ r,
  owner @{PROC}/@{pid}/fd/ r,
  profile dbus {
    include <abstractions/nameservice-strict>
    @{bin}/dbus-launch   mr,
    @{bin}/dbus-send     mr,
    @{bin}/dbus-daemon  rPx,
    owner @{HOME}/.dbus/session-bus/@{hex}-[0-9] w,
    include if exists <local/xdg-settings_dbus>
  }
  include if exists <local/xdg-settings>
```
This code block is not existent in the original profile. It reappears with every update even after manually deleting it. Why is that?

**Comment by roddhjav** [comment]
That is because of the [stack directive](https://apparmor.pujol.io/development/directives/#stack):

https://github.com/roddhjav/apparmor.d/blob/e15bdcc9ad71f88d935e77efe611ca57bbab75a8/apparmor.d/profiles-s-z/signal-desktop#L37-L38

**Comment by curiosityseeker** [comment]
Thanks, I had seen that. But so far I had only been familiar with stacking as used, e.g., in the `firefox` profile regarding `firefox-glxtest` and `firefox-vaapitest`. 

So the directive  `#aa:stack` adds the code of the profile to be stacked at the end of the parent profile, AFAIU. But what exactly is the difference and advantage over stacking as implemented in the `firefox`profile (i.e. without this directive)?  

And I don't understand this explanation:

> If X is set, the directive will conserve the x file rules regardless of the transition. Not enabled by default as it may conflict with the parent profile.

I fell over this as `aa-log` reports:

```
profile signal-desktop {
  /bin/xdg-mime ix -> xdg-mime, # no new privs no new privs

  owner @{user_config_dirs}/ibus/bus/ r,

        @{sys}/devices/@{pci}/oot_vga r,
  owner @{sys}/fs/cgroup/user.slice/user-@{uid}.slice/user@@{uid}.service/app.slice/app-signal\x2ddesktop@@{hex32}.service/cpu.max r,
}

profile xdg-settings {
  /bin/xdg-mime ix -> xdg-mime, # no new privs no new privs
}
```

**Comment by roddhjav** [comment]
> But what exactly is the difference and advantage over stacking as implemented in the firefoxprofile (i.e. without this directive)?

I have updated the doc about this. To sum up, it is not needed in firefox because the firefox profile because `firefox-vaapitest` is already included in `firefox`, wich is not true for `xdg-settings` and signal.

> And I don't understand this explanation:

Automatically adding `Px` and `ix` transition in a profile is a very effective way to have conflict between transitions as you can automatically add rule already present in the profile but with another transition (that is the famous apparmor error: `profile has merged rule with conflicting x modifiers`). `X` is an option in the directive either or not to include the rules.

> I fell over this as aa-log reports:

That is a good point, profile transition in the child profile will have to be recursively stacked.

> Shouldn't this be @{sys}/devices/@{pci}/boot_vga r,? I had seen this before. aa-log error?

Yes, it is a bug in `aa-log` can you get the raw log (directly from `audit.log`) so I can find the issue in aa-log.

**Comment by beroal** [comment]
> It reappears with every update even after manually deleting it. Why is that?

In Arch Linux, profiles in the system are overwritten because this is how the package is built. See also the `NoUpgrade` directive in the “pacman.conf”.

**Comment by odomingao** [comment]
If I understand stacking correctly, it is helpful only to prevent the child process from gaining privileges that are equivalent to the parent profile but not the other way around. So, for instance if a program has no new privs and the child profiles need way more access than the parent, is stacking even worth it versus having everything on the same profile?

**Comment by curiosityseeker** [comment]
> > It reappears with every update even after manually deleting it. Why is that?
> 
> In Arch Linux, profiles in the system are overwritten because this is how the package is built. See also the `NoUpgrade` directive in the “pacman.conf”.

Yes, I know that. This was not my problem  - the problem was that I thought that the profile was somehow badly processed resulting in a profile on my system different from the "original" one (so I manually "corrected" it). But that was before Alex pointed to the `#aa:stack` directive.

**Comment by curiosityseeker** [comment]
> If I understand stacking correctly, it is helpful only to prevent the child process from gaining privileges that are equivalent to the parent profile but not the other way around. So, for instance if a program has no new privs and the child profiles need way more access than the parent, is stacking even worth it versus having everything on the same profile (with ix)?

In that case you can call it with px or cx. With ix it has exactly the same permissions as the parent profile.

**Comment by curiosityseeker** [comment]
> > Shouldn't this be @{sys}/devices/@{pci}/boot_vga r,? I had seen this before. aa-log error?
> 
> Yes, it is a bug in `aa-log` can you get the raw log (directly from `audit.log`) so I can find the issue in aa-log.

`apparmor="ALLOWED" operation="open" class="file" profile="signal-desktop" name="/sys/devices/pci0000:00/0000:00:02.0/boot_vga"  comm="signal-desktop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="seeker" OUID="root"`

Perhaps the last / must be escaped?

**Comment by curiosityseeker** [comment]
> > But what exactly is the difference and advantage over stacking as implemented in the firefoxprofile (i.e. without this directive)?
> 
> I have updated the doc about this. To sum up, it is not needed in firefox because the firefox profile because `firefox-vaapitest` is already included in `firefox`, wich is not true for `xdg-settings` and signal.

Ah, thanks, I guess I'm beginning to understand. But I'm probably a bit slow on the uptake - what does "include" mean exactly? Yes, vaapitest and glxtest come packaged together with the firefox executable, nevertheless they are still separate executables like xdg-settings ...

> Automatically adding `Px` and `ix` transition in a profile is a very effective way to have conflict between transitions as you can automatically add rule already present in the profile but with another transition (that is the famous apparmor error: `profile has merged rule with conflicting x modifiers`). `X` is an option in the directive either or not to include the rules.

I'm sorry but I still don't understand. Perhaps you could illustrate it with the `signal-desktop` profile example. It contains:

```
#aa:stack X xdg-settings 
@{bin}/xdg-settings  rPx -> signal-desktop//&xdg-settings,
```

How would that differ from a directive without the `X`?

```
#aa:stack xdg-settings 
@{bin}/xdg-settings  rPx -> signal-desktop//&xdg-settings,
```

**Comment by odomingao** [comment]
> > If I understand stacking correctly, it is helpful only to prevent the child process from gaining privileges that are equivalent to the parent profile but not the other way around. So, for instance if a program has no new privs and the child profiles need way more access than the parent, is stacking even worth it versus having everything on the same profile (with ix)?
> 
> In that case you can call it with px or cx. With ix it has exactly the same permissions as the parent profile so that it would not be sufficient in your example.

"no new privs" prevents profile transitions with px/cx, so the only possible choices are making a huge profile where each program inherits the parent profile's confinement, or stacking.

**Comment by curiosityseeker** [comment]
> "no new privs" prevents profile transitions with px/cx, so the only possible choices are making a huge profile where each program inherits the parent profile's confinement, or stacking.

Correct. I somehow misread your remark "if a program has no new privs" - sorry!

**Comment by roddhjav** [comment]
> How would that differ from a directive without the X?

Without the `X` option, the profile in your comment: https://github.com/roddhjav/apparmor.d/issues/505#issue-2540160762
would have looked like this:
```
# Stacked profile: xdg-settings
  include <abstractions/consoles>
  include <abstractions/freedesktop.org>
  /usr/share/terminfo/** r,
  /etc/xdg/xfce4/helpers.rc r,
  /etc/machine-id r,
  /var/lib/dbus/machine-id r,
  owner @{HOME}/ r,
  owner @{HOME}/.Xauthority r,
  owner @{user_config_dirs}/xfce4/helpers.rc{,.*} rw,
  owner @{run}/user/@{uid}/ r,
  owner @{PROC}/@{pid}/fd/ r,
  profile dbus {
    include <abstractions/nameservice-strict>
    @{bin}/dbus-launch   mr,
    @{bin}/dbus-send     mr,
    owner @{HOME}/.dbus/session-bus/@{hex}-[0-9] w,
    include if exists <local/xdg-settings_dbus>
  }
```

**Comment by curiosityseeker** [comment]
Ah - thanks! I think now I've got it :+1:

**Comment by curiosityseeker** [comment]
> That is a good point, profile transition in the child profile will have to be recursively stacked.

Just a confirmation that the mentioned problem still exists:

```
profile signal-desktop {
  @{bin}/xdg-mime r,

  /bin/xdg-mime ix -> xdg-mime, # no new privs no new privs
}

profile xdg-settings {
  @{bin}/xdg-mime r,

  /bin/xdg-mime ix -> xdg-mime, # no new privs no new privs
}
```
