### ISSUE TITLE
Add glfw shared files to graphics abstraction

### ISSUE THREAD

**Issue by odomingao** [roddhjav/apparmor.d#508]
I was working on a profile for a game, and I saw that both the compositor and the game's profiles need access to glfw shared files: 

```
@{run}/user/@{uid}/glfw-shared-@{rand6} rw,
```

I'm creating an issue instead of a PR because I'm not sure whether this should go directly into the graphics abstraction, or into one of the other abstractions that are included in it.

**Comment by roddhjav** [comment]
As it is only used for game, just add it to the common/game abstraction. We can revisit it later if other software use it.
