### ISSUE TITLE
`mkinitcpio` can't create a UKI

### ISSUE THREAD

**Issue by beroal** [roddhjav/apparmor.d#535]
Here is the log of upgrading the system. What concerns me is that `mkinitcpio` doesn't have permissions to create a unfied kernel image. Luckily, the `mkinitcpio` profile is in the complain mode.

https://pastebin.com/YapmrYa4

**Comment by roddhjav** [comment]
Thanks, should be fixed now. I do agree that issue in this kind of profile can be very bad...
