### ISSUE TITLE
aa-logprof error

### ISSUE THREAD

**Issue by Cherkah** [roddhjav/apparmor.d#542]
`run0 aa-logprof` :
```
ERROR: Syntax Error: Unknown line found in file /etc/apparmor.d/abstractions/user-data line 26:
prompt owner @{HOME}/ r,
```

my apparmor.d-git  0.2835-1 log:
[aa.log](https://github.com/user-attachments/files/17227759/aa.log)

**Comment by roddhjav** [comment]
It is a logprof issue, not something I can help with. See #463
