### ISSUE TITLE
xdg-desktop-portal can't access .flatpak-info

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#557]
DENIED  xdg-desktop-portal open owner /.flatpak-info comm=pool-/usr/lib/x requested_mask=r denied_mask=r

Complain mode:
ALLOWED xdg-desktop-portal open owner /.flatpak-info comm=pool-/usr/lib/x requested_mask=r denied_mask=r

**Comment by roddhjav** [comment]
It should be fixed now. Can you confirm on your side? See #559 for the context.

**Comment by Stoppedpuma** [comment]
Thanks for the quick fix! It seems to be fixed on my end but I'll reopen if I run into the same issue today.
