### ISSUE TITLE
Apparmor.d-git package have conflicts with the latest Apparmor package from Arch Linux

### ISSUE THREAD

**Issue by EricLin0509** [roddhjav/apparmor.d#560]
I'm just tried to upgrade the system on my VM, but I got these messages:
`error: failed to commit transaction (conflicting files)
apprmor: /etc/apparmor.d/brave exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/chrome exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/chromium exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/element-desktop exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/epiphany exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/firefox exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/flatpak exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/foliate exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/loupe exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/msedge exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/nautilus exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/opera exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/plasmashell exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/signal-desktop exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/slirp4netns exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/systemd-coredump exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/thunderbird exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/transmission exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/unix-chkpwd exists in filesystem (owned by apparmor.d-git)
apprmor: /etc/apparmor.d/virtiofsd exists in filesystem (owned by apparmor.d-git)
`
The Apparmor package coming from [here](https://archlinux.org/packages/extra-testing/x86_64/apparmor/).

**Comment by roddhjav** [comment]
That's a good news. It means Arch package has been updated to apparmor 4.

To fix the conflict, remove this line: https://github.com/roddhjav/apparmor.d/blob/62d7d7af68f1570e5b778018ba2df2c628cd0298/cmd/prebuild/main.go#L41

I am going to wait for the package to move out of the testing repository to apply the change, as if I do it right now, it would break all user set-up that are a not using the testing repository.

**Comment by roddhjav** [comment]
Implemented with #569
