### ISSUE TITLE
Vesktop can't access xdg-desktop-portal-gtk

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#562]
Doesn't seem to give any logs but it uses the file picker built into electron instead of xdg-desktop-portal-gtk when uploading files.

**Comment by roddhjav** [comment]
That does not seems to be related to apparmor? I mean, vesktop can use any tool they want?

**Comment by Stoppedpuma** [comment]
I think this is probably an issue on vesktops end as setting the profile to complain doesn't seem to help, nor does removing the deny rules. I've since switched back to the flatpak though as it doesn't seem to have this issue.
