### ISSUE TITLE
Permission denied for users to edit crontab

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#564]
Enforcing:
DENIED  crontab mknod owner /tmp/crontab.mDhvck comm=crontab requested_mask=c denied_mask=c

Complain:
ALLOWED crontab mknod owner /tmp/crontab.wXwim5 comm=crontab requested_mask=c denied_mask=c
ALLOWED crontab open owner /tmp/crontab.wXwim5 comm=crontab requested_mask=wrc denied_mask=wrc
ALLOWED crontab//editor mknod owner @{run}/user/@{uid}/nvim.8164.0 comm=nvim requested_mask=c denied_mask=c
ALLOWED crontab//editor open /etc/xdg/nvim/sysinit.vim comm=nvim requested_mask=r denied_mask=r
ALLOWED crontab//editor open owner @{user_config_dirs}/nvim/init.lua comm=nvim requested_mask=r denied_mask=r
ALLOWED crontab//editor exec @{bin}/git -> crontab//editor//null-@{bin}/git comm=nvim requested_mask=x denied_mask=x
ALLOWED crontab//editor//null-@{bin}/git file_inherit owner /tmp/crontab.wXwim5 comm=git requested_mask=wr denied_mask=wr
ALLOWED crontab//editor//null-@{bin}/git file_mmap @{bin}/git comm=git requested_mask=r denied_mask=r
ALLOWED crontab//editor//null-@{bin}/git getattr owner @{user_config_dirs}/git/config comm=git requested_mask=r denied_mask=r
ALLOWED crontab//editor//null-@{bin}/git getattr /tmp/ comm=git requested_mask=r denied_mask=r
ALLOWED crontab//editor//null-@{bin}/git getattr / comm=git requested_mask=r denied_mask=r
ALLOWED crontab//editor unlink owner @{run}/user/@{uid}/nvim.8164.0 comm=nvim requested_mask=d denied_mask=d
ALLOWED crontab unlink /tmp/crontab.wXwim5 comm=crontab requested_mask=d denied_mask=d

**Comment by roddhjav** [comment]
Thanks, it should be fixed now.
