### ISSUE TITLE
nvimpager

### ISSUE THREAD

**Issue by tacerus** [roddhjav/apparmor.d#568]
Hi,

I use [nvimpager](https://github.com/lucc/nvimpager) via `PAGER=/usr/bin/nvimpager` as my pager for Git.
I tried to facilitate this by adding `nvimpager` to `@{pager_names}` in `tunables/multiarch.d/programs`, this resolved some messages upon Git operations, but now causes new ones.

Here just one example, there's many more:

```
type=AVC msg=audit(1729523648.281:16886): apparmor="ALLOWED" operation="getattr" class="file" profile="child-pager//null-/usr/bin/nvim//null-/usr/b
in/nvim" name="/usr/share/nvim/runtime/pack/" pid=35642 comm="nvim" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

I'm not sure if rules for `nvim` should go into the `child-pager` profile. I assume cleanest would be a full profile for `nvim` and then to delegate from `child-pager` to there?

**Comment by roddhjav** [comment]
`child-pager` was not using the `@{pager_path}` variable, hence the issue. I have now added support for nvimpager out of the box.
