### ISSUE TITLE
flatpak-app cannot execute programs in games dir

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#586]
I've gotten around this temporarily by setting a local owner override which works fine for games ran with proton / wine, but not for native linux games which execute with a shell script.

Examples:

DENIED  flatpak-app exec owner "/mnt/ss-zpool/applications/steam/steamapps/common/Counter-Strike Global Offensive/game/cs2.sh" comm=steam-runtime-l requested_mask=x denied_mask=x
DENIED  flatpak-app exec owner "/mnt/ss-zpool/applications/heroic/Factorio/start.sh" comm=gogdl requested_mask=x denied_mask=x

**Comment by roddhjav** [comment]
I think this could already be covered by the profile as long as you set `/mnt/ss-zpool/applications` in your `user_game_dirs`.
