### ISSUE TITLE
Graphics issue using apparmor.d with xe graphics driver

### ISSUE THREAD

**Issue by EricLin0509** [roddhjav/apparmor.d#601]
Here are the logs:

`DENIED  gnome-extensions-app open @{PROC}/sys/dev/xe/observation_paranoid comm=gjs requested_mask=r denied_mask=r
ALLOWED gnome-control-center open @{PROC}/sys/dev/xe/observation_paranoid comm=gnome-control-c requested_mask=r denied_mask=r
DENIED  gnome-control-center-print-renderer open @{PROC}/sys/dev/xe/observation_paranoid comm=gnome-control-c requested_mask=r denied_mask=r
DENIED  mutter-x11-frames open @{PROC}/sys/dev/xe/observation_paranoid comm=mutter-x11-fram requested_mask=r denied_mask=r
DENIED  ibus-x11 open @{PROC}/sys/dev/xe/observation_paranoid comm=ibus-x11 requested_mask=r denied_mask=r
DENIED  xwayland open @{PROC}/sys/dev/xe/observation_paranoid comm=Xwayland requested_mask=r denied_mask=r
DENIED  gnome-shell open @{PROC}/sys/dev/xe/observation_paranoid comm=gnome-shell requested_mask=r denied_mask=r
`

**Comment by roddhjav** [comment]
Thanks, should be fixed now.
