### ISSUE TITLE
Should xdg-open support be added in qbittorrent?

### ISSUE THREAD

**Issue by giovanniPepi** [roddhjav/apparmor.d#610]
Adding ` @{open_path}/xdg-open rpx,` to qbittorrent's profile solve denied requests when changing torrent files' location and "Open destination folder" in KDE plasma whcih uses xdg-open as backend.
This should also fix for any other DE that uses it

However I'm not sure if this is the safest solution, so I've opened this issue before sending a PR

**Comment by roddhjav** [comment]
That should be done with `@{open_path} rPx -> child-open,`. See https://apparmor.pujol.io/development/internal/#open-resources

**Comment by giovanniPepi** [comment]
> That should be done with `@{open_path} rPx -> child-open,`. See https://apparmor.pujol.io/development/internal/#open-resources

Thanks for the reply. I might have mistakenly written p as lowercase in the profile, that's why it wasn't opening.
