### ISSUE TITLE
iotop needs netlink raw

### ISSUE THREAD

**Issue by cboltz** [roddhjav/apparmor.d#615]
Running iotop on Tumbleweed, the audit.log shows denials for netlink raw. Needed rules:

     network (getattr) netlink raw,
     network (receive) netlink raw,
     network (send) netlink raw,

which can be merged to

     network (getattr, receive, send) netlink raw,

**Comment by roddhjav** [comment]
Would adding `network netlink raw,` be enough? and quite similar?

**Comment by cboltz** [comment]
That is a bit more permissive, but will of course also work.

**Comment by roddhjav** [comment]
Fixed with c7030f1
