### ISSUE TITLE
Podman can't exec libsubid.so.5 in enforcing, also can't exec reexec in complain

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#625]
Podman fails to exec libsubid.so.5 while in enforcing mode, in complain mode podman seems to fail reexec. This results in the only way I can run certain containers is after a teardown.

[podman-aa.log](https://github.com/user-attachments/files/18135748/podman-aa.log)

**Comment by roddhjav** [comment]
Your profile for podman is not part of this project. Out of curiosity, where does it come from?

**Comment by Stoppedpuma** [comment]
Hmm that's a great question, it would have to be apart of the default apparmor profiles then? Apologies for the false alarm.

**Comment by roddhjav** [comment]
There is a default profile for podman, however, it is an unconfined profile that only allow the new `userns` access. It should not have generated any issues.
