### ISSUE TITLE
evince profile and abstraction

### ISSUE THREAD

**Issue by beroal** [roddhjav/apparmor.d#63]
Hi. Why does `profiles-a-f/evince` not include `abstractions/evince`? I discovered that `profiles-a-f/evince` can't view DjVu and PostScript files without particular permissions which are present in `abstractions/evince`. Or these permissions may be added to `profiles-a-f/evince` since they are 3 lines.

**Comment by roddhjav** [comment]
Hi, I removed this abstraction (7377aed01627d3953aae9443601a77af12b7f2b6 ) since it was not used outside evince and was not very useful for evince too. The proper solution would be to integrate the missing rules into the evince profile (PR are welcome).

**Comment by beroal** [comment]
I don't have permission to link this issue to #78. Sorry, I should have done it in the commit message.
