### ISSUE TITLE
Flatpak not working

### ISSUE THREAD

**Issue by quuinnn** [roddhjav/apparmor.d#631]
Whenever I try and run a Flatpak with AppArmor enabled, it gives this linkat error. Running `aa-teardown` then restarting AppArmor temporarily "fixes" it for one boot. I tried removing every AppArmor profile containing the word Flatpak then rebooting, but that didn't work. I reinstalled apparmor.d after that so the profiles are still here. I'm on a fully updated EndeavourOS (Arch Linux based) system, using linux-hardened, and switching kernel to one without a hardening patch applied doesn't fix the issue. And the command, `sudo aa-log -R -s` prints out nothing but a newline

``` sh
❯ flatpak run org.qbittorrent.qBittorrent/
error: linkat: No such file or directory
```

**Comment by roddhjav** [comment]
Duplicated with #614, currently investigating.
