### ISSUE TITLE
gpg decryption fails with apparmor enabled - no pinentry, no secret key

### ISSUE THREAD

**Issue by bcmertz** [roddhjav/apparmor.d#66]
Hi! Thank you for this excellent repo! I'm curious if there might be something that I'm doing wrong when it comes to using gpg and these apparmor profiles. I find that with these profiles enabled gpg fails to decrypt files, and errors out with the following error:
```
gpg: public key decryption failed: No pinentry
gpg: decryption failed: No secret key
```
This is able to be done successfully without apparmor enabled. GPG has its directory at ~/.gnupg with regular file permissions, all binaries are located where expected.

I tried adding execute permission for pinentry to all gpg profiles in this repo as 
```
  /{usr/,}bin/pinentry{,-*}     rPx,
``` 
truthfully not entirely sure about the proper arguements(? rPx, rix, etc?)

Any help is greatly appreciated, thank you again!

edit: seeing the following in aa-log
`DENIED  pinentry file_mmap /usr/bin/bash comm=pinentry requested_mask=r denied_mask=r`

**Comment by bcmertz** [comment]
Closing - issue was I didn't have all of the pinentry profiles, just the one pinentry profile

**Comment by bcmertz** [comment]
Reopening because I realized I was mistaken, I had to add  `/usr/bin/bash r,` to the pinentry profile to get gpg decryption working

**Comment by roddhjav** [comment]
Thank for the bug report, I will add the rule to `pinentry`.
To not block on each apparmor raise you should probably configure the project in `Complain mode`, that will allow you to test the profiles with your system, and to easily see any issue without blocking the execution of a program.

**Comment by bcmertz** [comment]
Thank you very much for the help, I'll definitely try Complain mode! I really appreciate this project 😊
