### ISSUE TITLE
Debian 10 have no `@{run}` tunable

### ISSUE THREAD

**Issue by nobodysu** [roddhjav/apparmor.d#7]
```
debian11$ grep -rI '@{run}' /etc/apparmor.d/tunables/
/etc/apparmor.d/tunables/run:@{run}=/run/ /var/run/
debian11$ grep -rI 'tunables/run' /etc/apparmor.d/tunables/
/etc/apparmor.d/tunables/global:#include <tunables/run>
```

Close if Buster support is dropped. It's still very much around however.

**Comment by roddhjav** [comment]
I have never supported Debian 10, that is too much work for a project that is still young to support multiple version of each distribution.

As you guest by yourself, you simply need to add the variable in a tunable to make it work. You might also need to include other newer abstractions.

**Comment by nobodysu** [comment]
This drop-in works perfectly:
```
debian10$ cat /etc/apparmor.d/tunables/xdg-user-dirs.d/run 
@{run}=/run/ /var/run/
```
I won't submit it cause it's not universal cross-system.

**Comment by nobodysu** [comment]
Same thing on Ubuntu LTS. This is a problem.

**Comment by roddhjav** [comment]
Compatibility with Ubuntu are handled in the `configure` script: https://github.com/roddhjav/apparmor.d/blob/3430e3df90fb5db1ce184443d1c097699fa93962/configure#L77 it adds the `run` tunable and other missing abstractions.
