### ISSUE TITLE
pick should install profiles for called helper applications as well

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#77]
The instructions for "Partial install" says that `pick` "will also install required abstractions and tunables". It does that, indeed, but it does **not** install profiles for helper applications called from the main application. 

Example: I installed the profile for `zram-generator`which contains the following lines:

```
/{usr/,}bin/systemd-detect-virt     rPx,
/{usr/,}lib/systemd/systemd-makefs  rPx,
```
and the latter one is calling:
```
/{usr/,}{s,}bin/mkswap     rPx,
/{usr/,}bin/mkfs.*         rPx,
```

Unfortunately, those profiles were not installed by `pick`. I think that's a bug as those missing profiles will probably lead to errors.

**Comment by roddhjav** [comment]
Hi, So ultimately you are right. This feature needs to be added to the `pick` script. However, as I focus on the package installation, I currently do not have the time to work on this. But PR are more thank welcome.

**Comment by curiosityseeker** [comment]
Thanks, I understand! 

I'm a lousy coder at best but I will see what I can do.
