### ISSUE TITLE
tor

### ISSUE THREAD

**Issue by beroal** [roddhjav/apparmor.d#82]
There was `abstractions/tor` which I used to create my profile. It was deleted from this project. What are plans for Tor?

**Comment by roddhjav** [comment]
There is no plan for Tor. Just use [Whonix](https://www.whonix.org/). I removed the tor abstraction and profiles as they are maintained by other project (Whonix).

However, there is a plan to fully support Whonix. But this is still a work in progress.

**Comment by beroal** [comment]
I'm new to Whonix. It seems that Whonix is intended for client internet applications (web browsers, chats, email clients), but I run a public Tor relay (daemon). Whonix is heavyweight. Do you think Whonix has any advantages over a plain Tor relay in this use case? Do you know how to extract the Tor profile from Whonix without installing Whonix?

**Comment by roddhjav** [comment]
Ok, that make sense. I try to avoid putting not third party profile here this is why I removed them initially. You can just take the `system_tor` profile (and the `tor` abstraction) profile Whonix and it should work fine. They should also be the same than the one I removed in this project.

**Comment by beroal** [comment]
It seems that the Tor profile was created by Debian maintainers:

- https://sources.debian.org/src/tor/latest/debian/tor.apparmor-profile.abstraction/
- https://sources.debian.org/src/tor/latest/debian/tor.apparmor-profile/
