### ISSUE TITLE
aa-logprof partially broken even when installing specific profiles

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#87]
As discussed in #76 installing the profiles presented here breaks the AppArmor userspace tools as `@{exec_path}` is not supported. As I don't want to go without `aa-logprof` I only install **specific** profiles with `pick` and remove `@{exec_path}`. 

Unfortunately, even this approach breaks `aa-logprof` partially! That tool now only presents network- and ptrace-related rules but no longer path-related rules. Which means that creating new profiles becomes rather laborious as it's no longer possible to interactively add path rules. `aa-log` is unfortunately no proper substitute.

I've sifted through the code of `pick` but couldn't find anything. So something else must be the culprit. What am I missing?

**Comment by roddhjav** [comment]
The problem is indirectly due to `@{exec_path}`. In practice the source cause is that the python library behind `aa-logprof` does not parse variable used in profile attachment (and possibly too in profile header). This is a know bug in AppArmor. But has it is not trivial to fix, it has be open for years.

**Comment by curiosityseeker** [comment]
I'm not quite sure that I understand. Do you mean the [additional variables](https://github.com/roddhjav/apparmor.d/blob/master/CONTRIBUTING.md#apparmor-variables) introduced by this project?

If so - does that mean that it would be necessary to rewrite every profile by removing those additional variables?

**Comment by roddhjav** [comment]
No, I mean the variables defined in a profile preamble (just before the `profile ...` line) not the one in the tunables

To sum up, this issue might still be open for years as it is not easy to fix.

**Comment by curiosityseeker** [comment]
> No, I mean the variables defined in a profile preamble (just before the `profile ...` line) not the one in the tunables

Ah, I see - but, quite frankly, I'm not fully convinced. I had been using the libreoffice profiles (which originally come from Canonical) for some years. The *.soffice.bin profile contains variables ( `@{libreoffice_ext}` and `@{libo_user_dirs}` ) as well and they had never caused any trouble with aa-logprof. Similarly, I've been using `@{okular_ext} = [eE][pP][uU][bB] [pP][dD][fF]`
in my okular profile for some time without any problems. 

So I still think that there must be another culprit.

**Comment by curiosityseeker** [comment]
> EDIT: Note that I haven't tested the new version with regard to the `@{exec_path}` problem yet.

Unfortunately, this problem still exists.

**Comment by curiosityseeker** [comment]
Closing as fixed by upstream.

**Comment by Cherkah** [comment]
i'm facing issue with aa-logprof.

related to this post #87 i went straight to gitlab to report it: [gitlab aa bug n°342](https://gitlab.com/apparmor/apparmor/-/issues/342)

as this know issue takes long to be addressed, i was asking myself if you can propose a trick/patch so as to temper it ?! even if it is not related to apparmor.d 

see below my bugreport
[apparmor-bugreport-okwuv5j_.txt](https://github.com/roddhjav/apparmor.d/files/15247533/apparmor-bugreport-okwuv5j_.txt)

apparmor -V: 3.1.7-2
os: Endeavouros (archlinux)

**Comment by roddhjav** [comment]
It might be different, but you need to ensure you do not use variables in profile attachment. So, instead of:
```
profile foo @{bin}/foo {
```

You must have
```
profile foo /{,usr/}{,s}bin/foo {
```

In apparmor.d it is automatically resolved during the package build time. You can compare the generated profile and the one in the code. Eg for [aa-log](https://github.com/roddhjav/apparmor.d/blob/main/apparmor.d/profiles-a-f/aa-log), and `/etc/apparmor.d/aa-log` in you computer.

**Comment by Cherkah** [comment]
thank to your answer, but maybe you got me wrong. Contrary to the @curiosityseeker, i'm using only aa-logprof to create/custom my profil.

the issue consists of the impossibility of launching the aa-logprof command without it crashing. it's related to python. see my bugreport.

ps: I posted my problem here but apparently I should have created another one.
